### ISSUE TITLE
What do we want to call our Library?

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#10]
One idea: "Apple Pie"

**Comment by colinpmacarthur** [comment]
+1

**Comment by rypan** [comment]
If you want to continue the `pie` theme...you could name the versions after pies...

Apple Pie
Blueberry Pie
Cranberry Pie

:smile: 

I also like a word like `Union`...

**Comment by mjovel** [comment]
Anthem
Citizen
Monument

**Comment by jenniferthibault** [comment]
Some flag history nerdism perhaps? http://www.ushistory.org/betsy/flagfact.html

Betsy Ross
 > Cowpens
 >> Brandywine
 >>> Serapis

Maybe this is getting too obscure, but I like the idea of incorporating historical reference

**Comment by mollieru** [comment]
@jenniferthibault love the thinking here. One thing I wonder about changing the name: existing libraries we often reference - Materials, Bootstrap, Bourbon - their names don't change w releases, right?  Just wonder if it's confusing if we do a big promotion around "Betsy Ross" and then a few months later we start calling it "Cowpens" (also that's making me giggle). But if there's precedent to name releases uniquely, then I'm into it.

**Comment by msecret** [comment]
From a developer's perspective, if you change names based on release, it should serve a specific purposed. For instance, Ubuntu names new releases of it's OS with various animal or other names, it's purpose is make it easier to remember versions. The public communication includes both the name as well as the numbered version, so something like "Ubuntu v14 Saucey out now". It's important that the primary name, "Ubuntu", is always there and consistent. This still has the downside of confusing people what name belongs to which number.

Taking this back to the pattern library, it could be called "US Pattern Library" and each release could have a fun name: "US Pattern Library v4 Betsy Ross out now". Although a question to ask would be if the amount of versions this library has really warrants a second name. If you're releasing versions more then a year apart, the extra name might just increase confusion.

Also, I've rarely heard of actual frameworks and libraries using release names like OS's do, usually it's just numbered versions. This *could* mean that using a release name could create confusion among developers, but this hypothesis should be tested.

**Comment by msecret** [comment]
In terms of primary name, the front end community is known for random and abstract naming: "bourbon"/"neat", "ampersand", "Sass", "Susy", "Penguin", "Inuit", "Rizzo". Even libraries that could have concrete names like "chart lib" are often named something fun "Rickshaw". I think these names have a light and fun feeling. Another aspect about picking names like this is that the developers can design a really fun site to promote the tool. Like the "Penguin" library has a fun penguin illustration on it's site.

Depending on how we want to brand this, it might make more sense to have a more concrete, serious name which actually explains what this is: "US Pattern Library", "US Components", "US UI", etc. Or picking a more fun name, "Apple Pie", could insinuate that this library fits in with the front end world. It really depends on how this should be branded.

My personal opinion is to pick a name that has some sort of meaning as to what the library is. Good example of this: "Foundation", it provides a basic CSS foundation, "React", a framework for reactive programming, "Moment", working with dates in JS, "Howler", and audio library. I'll try and think of examples for this actual library.

**Comment by jenniferthibault** [comment]
All hail @msecret for naming precedent 101!

**Comment by juliaelman** [comment]
@msecret awesome points and agree that release names could be confusing to folks.

How about something "Eagle" related? It's something we've discussed previously too.

**Comment by mjovel** [comment]
Maybe rather than naming releases you could go for a hub and spoke approach for the library and component groupings kind of like Bourbon > Neat > Bitters > refills or atoms > molecules > organism , etc. It might be an interesting way to both fit-in to the front-end world while still making the library/frameworks intent known as well as explaining how each piece fits together as one cohesive unit?

**Comment by cew821** [comment]
I think @msecret is on the right track.

It feels kinda like there is something in "E pluribus unum" (out of many, one).

except latin... gross. and "Unum" on its own doesn't sound or look that cool.

**Comment by dhcole** [comment]
preamble

> an introductory, succinct statement of the principles at work

**Comment by carodew** [comment]
As long as we're in the expansive/generating lots of ideas part of the process, I think it would be cool to create a mindmap of ideas with branches connecting to different ideas. @ericronne, do you know if mural.ly can handle this? Or do you know of another collaborative program that might?

**Comment by ericronne** [comment]
Murally may be about as good a tool for that as any. What's your vision for
this piece?

**Comment by carodew** [comment]
This is a crude example, but something like this: http://tomreillya2courseworkblog.blogspot.com/2011/10/finding-my-brand-name.html

You start with the core concept in the center, then start branching off different idea threads. The goals is to get a collection of words and concepts related to the product, which can then serve as inspiration for clever name ideas. E.g. In the center we could put "US Pattern Library" (or whatever working title we're going with). One person might be inspired from the 'pattern' concept and branch off with 'flags', then different terms related to the US flag (Betsy Ross, Stars and Stripes, etc).

**Comment by ericronne** [comment]
Yep. Provided you begin with a sufficiently compact "core," murally should
work well for such an application. If it gets too large, you can select
everything and resize. Perhaps use the title tool for labeling, and connect
titles with lines (drag them over titles, notes or images in order to make
them "stick"). For an organic feel, you could even scan a rough base and
drop it in as a background. :) That help?

**Comment by carodew** [comment]
Yes, thanks @ericronne!

@mollieru et al. – do you think something like this would be useful? We shouldn't do the exercise if no one else sees the value in it (personally I like being able to see all the ideas in one place and being able to branch off of them, but that's just my preference).

**Comment by juliaelman** [comment]
@carodew +1 and great idea @ericronne!

**Comment by carodew** [comment]
Ok – I started a board here. Anyone should feel free to add, expand upon, or create derivatives of the ideas here: http://mur.al/Yx9XaOBG

**Comment by mollieru** [comment]
Just an update: sent a survey out to everyone on the Digital Service listserv. @mjovel + others, would love to get your input logged here as well:

https://www.surveymonkey.com/s/JX6LHCD

**Comment by cew821** [comment]
One more idea:

Fabric
> Stars
> > Stripes

**Comment by cfarm** [comment]
@mollieru how do we get on that listserv?

**Comment by jonraedeke** [comment]
Another reason for a short fun name would be for package managers like npm or bower. @contolini brought up the issue of packaging/delivery of the library in #48.

"Columns" is cool name with a double meaning, but is not unique enough for a namespace. "USUI" could work as an abbrev. for a long official name like "US Government UI Pattern Library"

**Comment by mollieru** [comment]
@cfarm looking into it! will get back to you.

**Comment by mollieru** [comment]
@cew821 for some reason, now all I can think of is this: https://www.youtube.com/watch?v=TJLcrYiJB14

<iframe width="420" height="315" src="https://www.youtube.com/embed/TJLcrYiJB14" frameborder="0" allowfullscreen></iframe>

**Comment by mollieru** [comment]
Thank you all for the input! Going to close this out for now as we've gotten oodles of good feedback and will report out.
