### ISSUE TITLE
Typo: Reset Password Screen

### ISSUE THREAD

**Issue by jenniferthibault** [18F/govt-wide-patternlibrary#100]
Have "at least"
![screen shot 2015-06-26 at 3 39 43 pm](https://cloud.githubusercontent.com/assets/11636908/8385874/a60b1d6a-1c19-11e5-967d-abb36bf346a0.png)

Consistent capitalization of "Your" at the beginning of the input field:
![screen shot 2015-06-26 at 3 40 33 pm](https://cloud.githubusercontent.com/assets/11636908/8385883/bba8d43c-1c19-11e5-9053-9cf4e3e3b6d6.png)

**Comment by colinpmacarthur** [comment]
Thanks! I've added this to our project workflow.
