### ISSUE TITLE
Typo: [Typography] Primary Nav Links

### ISSUE THREAD

**Issue by jenniferthibault** [18F/govt-wide-patternlibrary#101]
Navink should probably be a real word anyways.

![screen shot 2015-06-26 at 3 45 28 pm](https://cloud.githubusercontent.com/assets/11636908/8385969/6dd51ef4-1c1a-11e5-8559-5f70ccc03214.png)

**Comment by colinpmacarthur** [comment]
Thanks! We've added this to our project workflow.
