### ISSUE TITLE
Show full interactions for similar elements, and make sure to match styles. 

### ISSUE THREAD

**Issue by jenniferthibault** [18F/govt-wide-patternlibrary#102]
Match Styles of "Show SSN" and "Show Password" Elements in Forms.
"Show SSN" and "Show Password" seem like the same interaction, so could match in style and placement. 

![screen shot 2015-06-26 at 4 01 31 pm](https://cloud.githubusercontent.com/assets/11636908/8386257/dd652726-1c1c-11e5-860d-f8de45c1629d.png)
![screen shot 2015-06-26 at 4 01 40 pm](https://cloud.githubusercontent.com/assets/11636908/8386258/dd7409d0-1c1c-11e5-8928-a21f41989f43.png)

**Comment by mollieru** [comment]
Yea, good call! 

I think what you're seeing here (and is a good catch, which we should address) is snapshots of different places in the flow. 

*Step 1* 
- Arrive at a form which you haven't entered data into. 
- In the Form field, you see sample guiding text (in gray)
![image](https://cloud.githubusercontent.com/assets/3680494/8387246/0fa04f4c-1c25-11e5-8e0b-a842e51ac81b.png)

*Step 2* 
- Enter your data, form replaces digits w dots
![image](https://cloud.githubusercontent.com/assets/3680494/8387298/7af85d34-1c25-11e5-94fa-5ae4d7f7eab0.png)

**Comment by jenniferthibault** [comment]
Oh! Hadn't even looked at it that way, but you're right, it could also refer to the dummy text in the empty field. I was just noticing the link style of the "Show SSN" and "Show Password" text.

**Comment by mollieru** [comment]
More than just the style mismatch, you've also pointed out that we're not showing the full flow of the interaction consistently. Def something we can remedy!  Updating the title to match.

**Comment by colinpmacarthur** [comment]
Adding this to our project workflow. Thanks!
