### ISSUE TITLE
Currently, can't navigate directly to all [Input] and [Form Block] patterns.

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#104]
It's currently hard to navigate to specific Input and Form Block patterns. I'm a little worried our users might be missing them entirely, and for myself, I find I'm doing a lot of scrolling around a'command-F'ing to find specific ones. I know we're on hold for updating sidenav until we get more conclusive user input, just wanted this documented.

**Comment by colinpmacarthur** [comment]
Our usability testing didn't find any problems with folks navigating to input and form block patterns, but there are broader navigation problems we'll be working on this sprint.
