### ISSUE TITLE
Suggestion: Tablesaw for responsive tables

### ISSUE THREAD

**Issue by andrewmaier** [18F/govt-wide-patternlibrary#107]
Curious if we've thought about how our table styles might respond in various widths?
https://github.com/filamentgroup/tablesaw

**Comment by msecret** [comment]
There's lots of existing resources out there for responsive tables (such as the one Andrew posted above)> I would suggest an existing resource be used in the pattern library rather then building our own.

**Comment by jjoteal** [comment]
I second the guidance for responsive tables!

Also, many of the tables that I come across contain many more columns than the ones shown in the pattern library. Perhaps also include guidance on simple tables vs. complex tables?

**Comment by dannychapman** [comment]
:+1: for tablesaw

**Comment by colinpmacarthur** [comment]
Thanks so much! Added to the project's workflow.
