### ISSUE TITLE
Add media block component

### ISSUE THREAD

**Issue by maya** [18F/govt-wide-patternlibrary#108]
The media block is a highly reusable component composed of an image with text beside it. Our library does not include it and we should consider including it.

I also wanted to share part of a Component talk by Nicole Sullivan where she talks about “the anatomy of a good component”, and the media block component. https://vimeo.com/86928424#t=1301s

Slides from Nicole's talk:
![screen shot 2015-06-30 at 11 39 03 am](https://cloud.githubusercontent.com/assets/5249443/8438781/e34e9bce-1f1c-11e5-8451-dc3c7442353b.png)
![screen shot 2015-06-30 at 11 39 30 am](https://cloud.githubusercontent.com/assets/5249443/8438782/e352ffe8-1f1c-11e5-9ef4-bc83c816beff.png)
![screen shot 2015-06-30 at 11 40 24 am](https://cloud.githubusercontent.com/assets/5249443/8438780/e346f57c-1f1c-11e5-9267-34cccb807f94.png)
![screen shot 2015-06-30 at 11 41 15 am](https://cloud.githubusercontent.com/assets/5249443/8438779/e33492f6-1f1c-11e5-964b-59492baa102e.png)

**Comment by colinpmacarthur** [comment]
Thanks! Closing and adding to the backlog.
