### ISSUE TITLE
Move SASS generation outside of Jekyll

### ISSUE THREAD

**Issue by maya** [18F/govt-wide-patternlibrary#110]
Jekyll does not support source maps and they're pretty important bc they allow us to know where our styles are coming from: http://thesassway.com/intermediate/using-source-maps-with-sass 

We should disable Jekyll's generation of SASS and add it manually in the `./go` script. The we can add in source maps.

**Comment by colinpmacarthur** [comment]
Added this to the project workflow. (Trello icebox.)
