### ISSUE TITLE
Sample Product: VA Appeals Work Queue

### ISSUE THREAD

**Issue by KHarshawat** [18F/govt-wide-patternlibrary#115]
Here's a wireframe I made with the pattern library. It's a work-queue that we're working on for the Board of Veterans Appeals:

![work queue-11](https://cloud.githubusercontent.com/assets/6335546/8480750/816385f4-20ad-11e5-81e8-b83a3b3e38c3.png)

**Comment by mollieru** [comment]
Cool! Thank you @KHarshawat !

**Comment by colinpmacarthur** [comment]
Thanks for sharing!

**Comment by mpeter88** [comment]
Is that work queue the queue for a single worker, meaning the set of managed work items per person, like a standard work queue? 

For example, I can manage my work items, e.g.,  add/drag work items to my work list (sometimes only supervisors tod this), manage/update them, e.g. take actions on the case, delete those on which I'm no longer working (sometimes only supervisors do this). 

Or do all workers have to coordinate their work on the entire list of items?
