### ISSUE TITLE
Feedback: Consider including the Capital Framework (CFPB) pagination pattern

### ISSUE THREAD

**Issue by vz3** [18F/govt-wide-patternlibrary#116]
This may make the most sense for long documents and regulation rather than, say, search results.

Demo:
http://cfpb.github.io/cf-pagination/docs/

**Comment by carodew** [comment]
I think this is a great idea – I think long term it would be great to offer a few different solutions for various components with guidance on how to decide which to use.

**Comment by colinpmacarthur** [comment]
Thanks for the suggestion @vz3! I'm adding this to our project workflow.
