### ISSUE TITLE
Feedback: [Search results] Results count should be subtle

### ISSUE THREAD

**Issue by afeijoo** [18F/govt-wide-patternlibrary#118]
While useful, the results count isn't a worthy of a primary heading like an H2. 

See, for example, Google which uses a light grey, small font.

https://www.google.com/#q=test

**Comment by Scotchester** [comment]
:+1: but I think that space should be used for reminding the user what their search query was. I assume the query will remain in the search box, but in some of the layouts, the search box is narrow enough that a longer query would get cut off.

**Comment by colinpmacarthur** [comment]
Thanks so much @afeijoo and @Scotchester! I’ve added this suggestion to our project workflow.
