### ISSUE TITLE
feature request: list of dates/calendars

### ISSUE THREAD

**Issue by leahbannon** [18F/govt-wide-patternlibrary#12]
One of our biggest priorities coming up will be some kind of calendar or list of upcoming dates. If you can include this, I think it would have broad use. A lot of agencies need to share this info with the public for upcoming public hearings, events, closings, and deadlines for submitting applications or required info (ex: taxes or in the FEC's case, filing campaign finance info).

We have started working on this and could possibly collaborate.

**Comment by mollieru** [comment]
@leahbannon this is super helpful. Could you share a screenshot or sketch of an example or two? Totally fine if it's low-fidelity.

**Comment by carodew** [comment]
Ditto screenshots/wireframes. I'd like to know more about what areas in the site the calendar would appear and then think about how that can be generalized to uses on other sites. And/or we can talk about it when we chat next week!

**Comment by leahbannon** [comment]
Example of the way agencies are currently doing this? Or examples of doing it well? 

Also meant to cc @noahmanger @jenniferthibault

**Comment by mollieru** [comment]
@leahbannon I think either would be a helpful start. Basically I think we need a little bit more context to ensure we design this in a way that is helpful for you guys!

**Comment by maya** [comment]
@leahbannon @mollieru As a reference, gov.uk found out that calling out the next holiday date was really useful for people. And the upcoming and past dates are listed below. This is how they do it:

![gov uk - dates](https://cloud.githubusercontent.com/assets/5249443/8013895/2667a1e4-0b81-11e5-8f6c-d05618d14f48.png)

https://www.gov.uk/bank-holidays

**Comment by leahbannon** [comment]
So here's a survey of some of the ways the most popular government websites display dates and calendars and oh my holy face palm. I learned that you can type any government website into google + the word "calendar" and get a lot of results. And they are not pretty. Now I need to go apologize to anyone who automatically follows my boards on Pinterest. Enjoy: 

https://www.pinterest.com/leahbannon/calendars-for-gov-good-bad-ugly/

**Comment by carodew** [comment]
This is great – thanks for sharing!

**Comment by mebates** [comment]
Here's an activity log we're working on at CFPB. For events in the past: 
http://beta.consumerfinance.gov/activity-log/

**Comment by noahmanger** [comment]
Love that Activity Log! I could definitely see a similar pattern on FEC.gov

**Comment by carodew** [comment]
I thought this was a nice example of a timeline as well, via [MailChimp Pattern Library](http://ux.mailchimp.com/patterns/lists#activity-timeline)

![screen shot 2015-06-12 at 4 28 56 pm](https://cloud.githubusercontent.com/assets/10144074/8139280/4ec0d42c-1120-11e5-9188-2a46cf8ba3f5.png)

**Comment by mollieru** [comment]
Oooh really like both CFPB's and the MailChimp example.

**Comment by carodew** [comment]
Closing this and putting into our workflow. Thanks!
