### ISSUE TITLE
Feedback: [Search results] Snippets should highlight matched search terms

### ISSUE THREAD

**Issue by afeijoo** [18F/govt-wide-patternlibrary#121]
Highlighting the words in the snippets and titles helps searcher quickly scan the results and determine why it matches their query.

**Comment by mollieru** [comment]
Great tip @afeijoo!  Do you have a few examples of where this is done well that you can point us to?

**Comment by afeijoo** [comment]
@mollieru https://duckduckgo.com/?q=tax+form+1040

**Comment by colinpmacarthur** [comment]
Thanks so much @afeijoo ! I’ve added this suggestion to our project workflow.
