### ISSUE TITLE
Feedback: Don't offer an option for side search bar

### ISSUE THREAD

**Issue by afeijoo** [18F/govt-wide-patternlibrary#122]
This limits the size of the search box. The search box in the layout elements is in the upper right-hand corner so the search box on the results page should remain in the upper right, or be larger and placed above the search results.

**Comment by mollieru** [comment]
@afeijoo thank you for this suggestion! Can you load in an image point us to the specific search bar layout you're responding to?

**Comment by afeijoo** [comment]
@mollieru https://pages.18f.gov/govt-wide-patternlibrary/assets/img/static/Search_Results_UI_v1.png

**Comment by mollieru** [comment]
@afeijoo @carodew @angel 

In the past design projects, I have had need for the search bar and related filters to stay static throughout long pages of search results, which is where this pattern is derived. Here's an old example: https://fbopen.gsa.gov/?q=graphic+design&data_source=&naics=&parent_only=&p=

Given that best practice suggest line width should be between 45 to 75 characters (http://webtypography.net/2.1.2, http://baymard.com/blog/line-length-readability), my sense is that there should still be enough screen real estate to do a side bar search when needed.  That said, sounds like we should also create a pattern for search results directly below the search bar, as there may be frequent need for this as well.

**Comment by colinpmacarthur** [comment]
Thanks for the suggestion, @afeijoo! I've added this suggestion to our project workflow so we can mull on it more.
