### ISSUE TITLE
Feedback: Use only one indicator to search within the search box

### ISSUE THREAD

**Issue by afeijoo** [18F/govt-wide-patternlibrary#123]
Displaying both a magnifying glass icon on the left and a button on the right (magnifying glass or 'search') is confusing. Searchers typically expect to see only the right-aligned option. The magnifying glass is most commonly used.

Examples: 
* http://www.bing.com/search?q=test
* https://duckduckgo.com/?q=test&ia=meanings
* https://www.google.com/#q=test

**Comment by colinpmacarthur** [comment]
Thanks! I've added this to our project workflow.
