### ISSUE TITLE
Feedback: Include a recommended width of the search box and make it as wide as possible

### ISSUE THREAD

**Issue by afeijoo** [18F/govt-wide-patternlibrary#124]
The 1/3 and 1/4 grids both appear to be pretty short. 

Make the search box *at least* 27 characters wide, so it can accommodate multiple words without obscuring parts of the user's query. Source: http://www.nngroup.com/articles/top-ten-guidelines-for-homepage-usability/

If only a portion of the text is visible at a time, it makes it difficult to review or edit what you’ve typed. In general, search boxes are better too wide than too short, so that users can quickly review, verify and submit the query.

**Comment by colinpmacarthur** [comment]
Thanks! I’ve added this suggestion to our project workflow.
