### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by mariamarrero** [18F/govt-wide-patternlibrary#125]
Using web app icons sounds like a good option. However, agencies may have the need for icons that are not included in that list. In that case, they may be forced to create their own icons. Perhaps we can also mention some specs for the icons if there is that need? 

Also, some agencies may have some security guidelines, block them and may not be able to use them.

**Comment by afeijoo** [comment]
+1 @mariamarrero. We've found that quite a few agencies block Font Awesome icons, especially those with older versions of Internet Explorer.

**Comment by mollieru** [comment]
Thank you @mariamarrero and @afeijoo !  Moving your comments over to https://github.com/18F/govt-wide-patternlibrary/issues/43 where discussion on this topic is underway.
