### ISSUE TITLE
Feedback: [Search Results] Indicate filetype before the title in the search results listings

### ISSUE THREAD

**Issue by afeijoo** [18F/govt-wide-patternlibrary#126]
Searchers should be able to quickly and easily identify the filetype. It is often place the the left of the page title in the search results listings.

Examples:
* http://www.bing.com/search?q=tax+form+1040
* https://duckduckgo.com/?q=tax+form+1040
* https://www.google.com/#q=tax+form+1040

**Comment by mjovel** [comment]
+1

We do this at fda using badges - 

http://google2.fda.gov/search?client=FDAgov&site=FDAgov&lr=&proxystylesheet=FDAgov&requiredfields=-archive:Yes&output=xml_no_dtd&getfields=*&ie=UTF-8&ulang=en&&access=p&sort=date:D:L:d1&entqr=3&entqrm=0&wc=200&wc_mc=1&oe=UTF-8&ud=1&q=pill+inmeta:gsaentity_filetypes%3DPDF&dnavs=inmeta:gsaentity_filetypes%3DPDF

**Comment by Scotchester** [comment]
I don't love it to the left of the title. I'd rather be able to scan the titles more easily, but I think that might be largely personal preference. I'd be curious to see user testing on this.

**Comment by colinpmacarthur** [comment]
Thanks so much all I’ve added this suggestion to our project workflow -- we'll need to mull over your suggestions to figure out the best way forward.
