### ISSUE TITLE
Color Palette and mood boards

### ISSUE THREAD

**Issue by mariamarrero** [18F/govt-wide-patternlibrary#127]
The mood boards contain very neat color palettes. Is the look and feel chosen only for the library or could these be choices for agencies to use? Some agencies may use colors that are similar, but not exactly, to meet internal color contrast requirements. 

If this helps, a great color contrast tool that I always use to meet contrast requirements for foreground and backgrounds colors (text and graphics) is http://webaim.org/resources/contrastchecker/.

My favorite is the Modern American :)

**Comment by mollieru** [comment]
Thanks @mariamarrero! Moving this comment over to the thread w feedback on the mood boards.
