### ISSUE TITLE
Feature request: add a Meta-text style

### ISSUE THREAD

**Issue by KHarshawat** [18F/govt-wide-patternlibrary#128]
I often need a separate text style for meta-information such as dates, authors, page counts, etc. This text often needs to be smaller than normal body text. Here's a screenshot for how FB uses meta-information:

![_1__facebook](https://cloud.githubusercontent.com/assets/6335546/8484197/4d09b244-20c4-11e5-941e-eadbc756d30e.png)

**Comment by msecret** [comment]
+1

**Comment by mollieru** [comment]
Thanks @KHarshawat ! Can you offer one or two more examples?  (As close to specific to the context you need in gov design work, if at all possible). 

I think I understand what you're asking, just want to make sure we're designing for the use cases you're talkin bout.

**Comment by colinpmacarthur** [comment]
If you have a chance to add another example or two, we can add this to the project workflow, @KHarshawat. Just want to make sure we're clear on what's useful. :smiley:
