### ISSUE TITLE
Suggestion: Display snippets as snippets in search results

### ISSUE THREAD

**Issue by afeijoo** [18F/govt-wide-patternlibrary#130]
Search result listings often use snippets to highlight the relevant part of the document, not full sentences or paragraphs.

Cake **candy** snaps pudding cotton **candy** ... **Candy** biscuit danish desert bonbon ...

**Comment by colinpmacarthur** [comment]
Thanks so much @afeijoo. I’ve added this suggestion to our project workflow.
