### ISSUE TITLE
Feedback: [Typography] verify feasibility of 75 character limit

### ISSUE THREAD

**Issue by mariamarrero** [18F/govt-wide-patternlibrary#131]
The spec "make sure lines of text don't exceed 75 characters, as they become harder to read beyond that point" is probably a requirement that may not be realistic for some agencies. Perhaps we can say something like: "The recommended character limit in a line of text is 75 characters. Beyond that point, they become harder to read."

**Comment by Scotchester** [comment]
Why wouldn't it be realistic?

**Comment by mariamarrero** [comment]
I am looking at the proposed Layout 2 in the library, which is a very common layout and the Main Content area is pretty wide. Unless the font is large, 75 characters seem pretty low. I don't disagree with the statement, I just think that we could make it sound less of a "must".

**Comment by Scotchester** [comment]
My personal opinion is that I've seen enough research to be sold on that guideline as a "must", but I recognize that it does necessitate some concessions when it comes to typical layouts. This is something I'm still trying to get everyone on board with in my own organization.

There are several ways that this can be tackled, from a design perspective:

- The main body paragraph width does not have to fill the entire available width in the layout column. One can simply set a max-width that equals the top end of the ideal range of character count, and let there be some extra margin on the right side.
  - The extra margin could be balanced between the left and right sides, or be placed entirely on the left, as well. The presence of other design elements to anchor things will somewhat dictate this decision.
  - The extra margin doesn't have to be wasted space, either. I'm fond of doing things like pulling floated images into margins like that. Also, you can still use the full width of the area when warranted, like when displaying a table of data.
- The main column width could be completely constrained to the max paragraph width. This might result in a narrower overall page width than people might normally expect, but that's not necessarily a problem, if the design serves the user. One potential drawback to this, though, is that it would restrict the ability to have subgrid layouts within the main content column – e.g., it might become unrealistic to have three-column sections _within_ the main content column.

**Comment by colinpmacarthur** [comment]
Thanks for the thoughts, Scott and Maria! We'll add this to our project workflow.
