### ISSUE TITLE
Suggestion: remove Hero unit from [Layouts]

### ISSUE THREAD

**Issue by mariamarrero** [18F/govt-wide-patternlibrary#133]
Some of the layouts contain a "Hero Unit" that might be used for Carousels, sliders or rotators (other names). I would recommend removing this section as there are a few issues with using them. Some of the issue we have identify when we had them on our website are:

- They use prime page real estate that could be used for more effective content.
- Some people focus on one image in a "Hero section" and associate it with the host site, whether or not it relates to that site.
- They're hard to use on some mobile devices.
- They're difficult to make universally accessible for keyboards and all types of assistive technologies.
- They're distracting for people with certain cognitive disabilities; "Hero sections" impede their ability to complete tasks.
- They don’t always engage site visitors because:
- Many people find them annoying.
- Many people don't scroll through or use them, so they miss important information.

**Comment by Scotchester** [comment]
To play devil's advocate: heroes aren't necessarily for fanciness like carousels/sliders/rotators. They can serve as simple introductory material for the page. Here are a couple examples from our work:
- http://www.consumerfinance.gov/you-have-the-right/
- http://www.consumerfinance.gov/owning-a-home/

We've found that we usually want to drop the illustration at mobile sizes, so the hero area doesn't take up nearly the entire screen.

**Comment by colinpmacarthur** [comment]
Thanks @Scotchester and @mariamarrero! We'll have to do some thinking about the hero unit -- I've added this suggestion to our project workflow.

**Comment by maya** [comment]
+1 @Scotchester hero units and carousels are two different things
