### ISSUE TITLE
Suggestion: Include time stamps in search results

### ISSUE THREAD

**Issue by afeijoo** [18F/govt-wide-patternlibrary#134]
Including date stamps, when known, can help searchers determine the relevance of search results. Example:

Washington Nationals on Yahoo! Sports - News, Scores ...
sports.yahoo.com/mlb/teams/was/
*2 days ago* - Comprehensive and up-to-date Washington Nationals news, scores, schedule, stats and roster.

**Comment by Scotchester** [comment]
:+1:

**Comment by colinpmacarthur** [comment]
Thanks so much! I’ve added this suggestion to our project workflow.
