### ISSUE TITLE
Question: Text over images

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#139]
In my experience with 508, I've always been dinged for text that overlays images because it doesn't pass contrast ratio requirements. Not sure if this standard will vary across agencies, just know that I've had trouble with this type of treatment in the past.

![image](https://cloud.githubusercontent.com/assets/12192706/8500708/993376f2-216c-11e5-8063-101582442b45.png)

**Comment by Scotchester** [comment]
Could consider recommending that text overlaid on an image always include a drop shadow to help ensure it remains readable.

**Comment by mollieru** [comment]
Good tips guys! CC @angel

**Comment by colinpmacarthur** [comment]
Many thanks! I have added this issue to our project's workflow so it may possibly be addressed in future versions of the library.
