### ISSUE TITLE
Add Bourbon/Neat to pattern library repo

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#14]
After talking with @maya, we're planning on moving forward to using [Bourbon](https://bourbon.io/) and [Neat](https://neat.bourbon.io/) for the pattern libraries own infrastructure.

**Comment by cew821** [comment]
Love this choice. I ❤️ bourbon/neat

**Comment by juliaelman** [comment]
@cew821 we do too and thanks for the endorsement! :+1:
