### ISSUE TITLE
Feedback: Hover Link Style

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#140]
Is the hover link style the style for both body copy and default links? Needs to be more clear.

![image](https://cloud.githubusercontent.com/assets/12192706/8500788/659ca9ca-216d-11e5-9e26-092f3803dff7.png)

**Comment by colinpmacarthur** [comment]
Many thanks! I have added this issue to our project's workflow so it may possibly be addressed in future versions of the library.
