### ISSUE TITLE
Feedback: Grid column pixel measurements

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#141]
On the grid layout graphic: https://pages.18f.gov/govt-wide-patternlibrary/layout-system/#grids

Include the pixel measurements for all columns?

**Comment by carodew** [comment]
We've put the notations in ratios because the grid is responsive. Would pixel dimensions allow you to do something differently?

**Comment by jjoteal** [comment]
I was thinking that pixel dimensions might be helpful when setting up a Photoshop file for the desktop version of the site. The guides could set accordingly. Maybe another suggestion might be providing a downloadable PSD file that already has the grid built in?

**Comment by colinpmacarthur** [comment]
Many thanks! I have added this issue to our project's workflow so it may possibly be addressed in future versions of the library.
