### ISSUE TITLE
Feedback: Layout 2

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#142]
https://pages.18f.gov/govt-wide-patternlibrary/layout-system/#layouts

For layout #2, change the "Left Nav" text to "1/3" and the "Main Content" to "2/3" -- then users won't feel like they should include left nav in that space, as it could also be used for other content. Maybe place layout #2 and layout #4 together since they are related?

**Comment by colinpmacarthur** [comment]
Many thanks! I have added this issue to our project's workflow so it may possibly be addressed in future versions of the library.
