### ISSUE TITLE
Feedback: Button States

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#143]
Possible to group the various states for the buttons together? In other words, show the primary button default state and then all the various states side-by-side. Or if many of the various states are shared by many of the buttons, perhaps have some sort of table layout of the states?

**Comment by carodew** [comment]
I believe @maya was working on this for the next release, am I correct?

**Comment by maya** [comment]
This is done here: https://github.com/18F/govt-wide-patternlibrary/pull/137
