### ISSUE TITLE
508: Text Input Success

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#144]
Not sure if the green will meet 4.5:1 contrast ratios. I've been pinged for this before, but maybe standards vary across agencies?

**Comment by carodew** [comment]
Yep! We'll definitely be checking the colors for contrast – a lot of the colors are 'for now' while @angel works on branding.

**Comment by colinpmacarthur** [comment]
I know @angel's working on the colors in general (and accessibility is certainly a factor in those decisions), so I'm closing this out.
