### ISSUE TITLE
Feedback: Input Error Symbol

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#145]
Consider using an ! rather than an x for the error symbol, since x is more frequently associated with close.

![image](https://cloud.githubusercontent.com/assets/12192706/8500993/6264883e-216f-11e5-819b-a241c33d78f6.png)

**Comment by colinpmacarthur** [comment]
Many thanks! I have added this issue to our project's workflow so it may possibly be addressed in future versions of the library.
