### ISSUE TITLE
Feedback: Label style

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#146]
https://pages.18f.gov/govt-wide-patternlibrary/elements/#labels

Because the labels are color and also have rounded corners, they sort of look like buttons. Maybe they are and could be clickable? If not though, perhaps consider just using a light grey background or square corners so they are more distinguished from buttons?

**Comment by colinpmacarthur** [comment]
Many thanks! I have added this issue to our project's workflow so it may possibly be addressed in future versions of the library.
