### ISSUE TITLE
Feature Request: Breadcrumb guidance

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#148]
Include breadcrumb style guidance in the Headers & Navigation section?

**Comment by colinpmacarthur** [comment]
@jjoteal: There are (sort of) breadcrumb suggestions built into Header Nav / Complex / Active. What other suggestions would be most useful?

**Comment by jjoteal** [comment]
Ahhhh, I see. I'm assuming breadcrumbs are recommended on all navigation systems?

Perhaps include recommendations on breadcrumb text styling, > indicators, and how to handle breadcrumbs in cases where "pages" are shared between multiple sections? The last one is a usability issue, so not sure if it should be included in the pattern library...

**Comment by maya** [comment]
I think we may want to consider adding a breadcrumbs into its own component in order to add the information @jjoteal is talking about. I think it may get lost with everything in the headers/navigation.

**Comment by colinpmacarthur** [comment]
Makes sense to me. I included them with the header and nav because they're
usually deployed there. That said, they're easy to separate and I can
definitely understand your arguments.

On Tue, Jul 7, 2015 at 12:19 AM, Maya Benari <notifications@github.com>
wrote:

> I think we may want to consider adding a breadcrumbs into its own
> component in order to add the information @jjoteal
> <https://github.com/jjoteal> is talking about. I think it may get lost
> with everything in the headers/navigation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/govt-wide-patternlibrary/issues/148#issuecomment-119068735>
> .
>



-- 
*Colin MacArthur*
Experience Design, 18F
(617) 283-8166

**Comment by colinpmacarthur** [comment]
Many thanks! I have added this issue to our project's "icebox" so it may possibly be addressed in future versions of the library.
