### ISSUE TITLE
Feedback: need more guidance on Complex Navigation

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#149]
Include guidance on if the word "Topic" in this case should be clickable to a landing page or if it is just a header? 

![image](https://cloud.githubusercontent.com/assets/12192706/8501188/0be0c926-2171-11e5-9945-efc2350cb84c.png)

**Comment by dannychapman** [comment]
Also, is there any guidance on this for hover vs click state, or both? I'd advocate for click vs hover for both accessibility (motor impairment) and touch screen devices. OK if hover works too I guess.

**Comment by colinpmacarthur** [comment]
@dannychapman and @jjoteal: When we were wire-framing this, we were thinking users would click on the top-level links to reveal the mega menus (for the reasons you suggest). The wireframe annotations are in the process of migrating into nicely worded guidance for each component.

**Comment by maya** [comment]
@colinpmacarthur It sounds like @jjoteal is referring to top-level link "Topic" while you're referring to the dropdown link "Nav link 1". This also occurs in the footer navigation.

@dannychapman we use a darker color for hover states on links. Serif links have a dotted underline for links and solid underline on hover (along with the darker color). Not sure if we've considered active states for plain links. We have for buttons. What would you suggest?

**Comment by dannychapman** [comment]
For Nav link 1, perhaps a focus / active state, same as hover, or perhaps slightly darker / stronger?

**Comment by colinpmacarthur** [comment]
Ah, yes @maya, I misread @jjoteal's comment. Sorry about that! 

Whitehouse.gov and uspto.gov don't make their "Topics" headings clickable. I agree with their decision. When the children of each topic are already displayed, I doubt that landing pages for each topic would be used much.

**Comment by colinpmacarthur** [comment]
Sounds like the conclusion here is that:
- "Topic" links in the navigation shouldn't be clickable (like they aren't in the current version of the footer).
-  Users should click on (not hover over) the top-level links to reveal the mega menus
Thanks for helping us clarify, @jjoteal and @dannychapman.
