### ISSUE TITLE
Feedback: Checkbox + Radio Button vertical spacing

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#150]
The vertical spacing between checkboxes and radio buttons seems a little too generous?

![image](https://cloud.githubusercontent.com/assets/12192706/8501242/ad8f5c2e-2171-11e5-84e1-7cfdcfd1c131.png)

![image](https://cloud.githubusercontent.com/assets/12192706/8501248/b95efd0c-2171-11e5-8307-25275bc95e6e.png)

**Comment by Scotchester** [comment]
I'd disagree, if that's how they would be spaced on a touch device, and it's probably not worth changing the spacing via media query for different devices.

**Comment by carodew** [comment]
Agree with @Scotchester re: touch targets. As long as the negative space surrounding the checkboxes/radio button group is larger than the space between the options, they'll still look like a group.

**Comment by colinpmacarthur** [comment]
Thanks for the feedback @jjoteal! I agree with @Scotchester -- we're trying to make sure there's enough space for touch targets on a mobile device. I think we'll close this issue for now, but will keep an eye out for confusion around the radio button/checkbox spacing during usability testing with end users.
