### ISSUE TITLE
Feedback: Add 'Header' to Form blocks

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#152]
https://pages.18f.gov/govt-wide-patternlibrary/components/#forms-blocks

Include a style for the block header? For example, in the address example, include a top header for "Address" that displays the name of the block?

**Comment by andrewmaier** [comment]
I will admit to still using this format for address blocks even after I've seen users struggle with it in usability tests. :-/ 
![screen shot 2015-07-06 at 11 06 09 am](https://cloud.githubusercontent.com/assets/2970/8525479/19747d2a-23cf-11e5-9ffe-ff7d69b6a4ba.png)

**Comment by carodew** [comment]
@andrewmaier what do they struggle with, specifically?

**Comment by andrewmaier** [comment]
@carodew The labels below the fields confused them. In general, the users I observed read forms vertically, top to bottom, and struggled if they had to scan up or recall earlier information. Any horizontal movement (columns) was difficult for them.

**Comment by andrewmaier** [comment]
Related: See Dana Chisnell's "Universal Tenets of North American form fillers," that I referenced here: https://www.civicquarterly.com/article/paper-cut-the-bleeding-edge-of-government-forms/

**Comment by colinpmacarthur** [comment]
Many thanks! I have added this issue to our project's "icebox" so it may possibly be addressed in future versions of the library.
