### ISSUE TITLE
Question: Header/Footer

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#153]
Per the patterns, are you recommending that social media icons only be placed in the footer?

**Comment by colinpmacarthur** [comment]
I think we put social media icons in the footers because most govt. websites do, too. That said, I don't think they have to be there and I (personally) don't have a problem with them being elsewhere.

**Comment by colinpmacarthur** [comment]
(Hopefully we answered your question @jjoteal -- if not, feel free to reopen the issue.)

**Comment by jjoteal** [comment]
Yep -- you answered it. Just wanted to make sure there was nothing preventing folks from including social icons in the header, as I am frequently asked for guidance on that.
