### ISSUE TITLE
Feature Request: Type size / line height calculator

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#154]
Include a link to a resource like http://www.pearsonified.com/typography/ so users can calculate the proper type size:line height ratio (if they decide to alter the font sizes per their agency style guidelines, etc.)

**Comment by dannychapman** [comment]
:100:

**Comment by Scotchester** [comment]
That's an awesome tool!

**Comment by colinpmacarthur** [comment]
Many thanks! I have added this issue to our project's "icebox" so it may possibly be addressed in future versions of the library.
