### ISSUE TITLE
Feedback: Style for sortable table column headers

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#156]
https://pages.18f.gov/govt-wide-patternlibrary/elements/#tables

Include style for column headers that sort the column data below

**Comment by carodew** [comment]
@KHarshawat submitted a wireframe showing this concept in #115.

**Comment by colinpmacarthur** [comment]
Many thanks! I have added this issue to our project's "icebox" so it may possibly be addressed in future versions of the library.
