### ISSUE TITLE
Feedback: Accordion expand/collapse symbol

### ISSUE THREAD

**Issue by jjoteal** [18F/govt-wide-patternlibrary#157]
https://pages.18f.gov/govt-wide-patternlibrary/components/#accordions

Worried that the chevron icon is too close to the dropdown icon.

I've come across this in Ed, where I've had a dropdown menu listed at the first element in an accordion. The result was 2 down-facing chevrons right next to each other. I ended up changing the chevron for the accordion to a plus/minus symbol for expand/collapse to address.

![image](https://cloud.githubusercontent.com/assets/12192706/8501497/0f77ed32-2174-11e5-8545-a8d067b1519f.png)

**Comment by dannychapman** [comment]
LGTM!

**Comment by mollieru** [comment]
Thanks @jjoteal ! Moving this to https://github.com/18F/govt-wide-patternlibrary/issues/36 where some convo on Accordion styling is under way.
