### ISSUE TITLE
Feature request:  A-Z navigation bar

### ISSUE THREAD

**Issue by mariamarrero** [18F/govt-wide-patternlibrary#160]
A few agencies tend to use the A-Z navigation bar with anchor links to help brake up extensive content in alphabetical order. It would be helpful to add this component to the library as well. Example: https://www.usa.gov/federal-agencies/a

**Comment by colinpmacarthur** [comment]
Generally open, but feel a bit cautious about encouraging alphabetical indices. They're useful when they match users' mental models, but are easy to implement even when categorization or a search feature would make more sense. Check out p. 99 or http://media.nngroup.com/media/reports/free/Site_Map_Usability_2nd_Edition.pdf for thoughts.

**Comment by carodew** [comment]
I'm thinking long-term we may want to offer a small sample of navigation schemes with guidance on best implementations.

**Comment by colinpmacarthur** [comment]
Many thanks! I have added this issue to our project's "icebox" so it may possibly be addressed in future versions of the library.
