### ISSUE TITLE
[Typography] Reconsider specifying font sizes in pixels

### ISSUE THREAD

**Issue by AccessForAll** [18F/govt-wide-patternlibrary#163]
* Only percentages or ems scale well for people who need to magnify (for example, low-vision or aging eyes) or decrease (for example, macular degeneration) font sizes for readability.

* Some people use assistive technologies for improving readability when using an app versus a website, or because zooming in or out within a browser is insufficient for their needs.

* Consider specifying percentages (preferable) and/or ems; refer designers/developers to http://pxtoem.com.

* See “Support the Ability to Resize Text”: http://simplyaccessible.com/article/resize-text/

**Comment by carodew** [comment]
Absolutely! Fonts will be specified in ems in the code – we are doing research right now into whether visual designers using the library would like to see pixel dimensions as a convenient reference for their mock ups, knowing that they'll be translated into ems in production.

**Comment by carodew** [comment]
Closing this as it's being addressed in workflow.
