### ISSUE TITLE
[Typography] Encourage the use of fonts that support readability for all people

### ISSUE THREAD

**Issue by AccessForAll** [18F/govt-wide-patternlibrary#164]
* Certain fonts can cause readability and comprehension problems for people who have cognitive difficulties, dyslexia, etc. For example, see the difference in the word “Ill” when displayed in Verdana versus Arial.

* See “Fonts Designed for On-Screen Viewing”:
     * http://webaim.org/techniques/fonts/#verdana
     * http://webaim.org/techniques/fonts/#readability

**Comment by colinpmacarthur** [comment]
I believe the library's font suggestions are under discussion and the final decision will factor in readability considerations. Many thanks!
cc: @angel
