### ISSUE TITLE
[Typography] Reconsider using a dotted underline for body links’ normal appearance

### ISSUE THREAD

**Issue by AccessForAll** [18F/govt-wide-patternlibrary#165]
* Specifying links within the body of a document to have a dotted underline and hover as underline changes the semantics/natural display of links.

* Before CSS is applied, items with a dotted underline indicate that they’re definitions rather than links. This change can confuse most people—especially people with cognitive impairments—since they’re used to "regular" underlined text for links.

* The dotted appearance can also be difficult to see and/or confuse people with low-vision, even when they magnify text.

* See The Paciello Group’s information on HTML5 semantics: http://www.paciellogroup.com/blog/2011/11/html5-semantics-and-accessibility/

**Comment by colinpmacarthur** [comment]
Many thanks! I have added this issue to our project's "icebox" so it may be addressed in future versions of the library.
