### ISSUE TITLE
[Elements/text inputs] The error explanation text is too far to the right of the input box

### ISSUE THREAD

**Issue by AccessForAll** [18F/govt-wide-patternlibrary#169]
* The location is problematic for people who use screen magnification software, people who have cognitive impairments, and people who are using small screens.

* Reconsider placing the error text above the input box.

**Comment by maya** [comment]
Related: https://github.com/18F/govt-wide-patternlibrary/issues/38#issuecomment-119335648

**Comment by mollieru** [comment]
Adding this to convo on this topic here https://github.com/18F/govt-wide-patternlibrary/issues/38
