### ISSUE TITLE
[Elements/checkboxes] Reconsider the colors for checkbox selected state

### ISSUE THREAD

**Issue by AccessForAll** [18F/govt-wide-patternlibrary#170]
The checkbox “checked”/selected state may not have enough contrast, especially for a such a small-sized item.
     * Agency standards may call for higher contrast requirements.
     * This color combination could be washed out by light/difficult for people on older mobile devices..
     * The contrast could be problematic for people with low-vision.

Note that this applies to radio buttons as well.

**Comment by colinpmacarthur** [comment]
Many thanks! I have added this issue to our project's "icebox" so it may be addressed in future versions of the library.
