### ISSUE TITLE
[Form Patterns] Encourage the use of submit buttons with the form elements

### ISSUE THREAD

**Issue by AccessForAll** [18F/govt-wide-patternlibrary#171]
People who navigate by keyboards or other non-mouse devices need a submit button with form elements, whether an element appears alone or as a part of a larger form. When forms rely on scripting to submit a form or activate a function, people who don't use mice can unintentionally trigger the submission/activation.

* See JavaScript jump menus, WebAIM: http://webaim.org/techniques/forms/controls#javascript

**Comment by mollieru** [comment]
@AccessForAll thanks for the handy link + advice! Can you give us a screenshot or more detail on where you're seeing form patterns that do not currently not offer a submit button?

**Comment by maya** [comment]
@mollieru previously we included `<button type="submit">Submit</button>` and `<input type="submit">` in buttons but the team decided to take them out bc they looked visually the same as other buttons. Now we just show `<button>Static</button>`. This may be something we'd want to include in usage, if we're not going to show in the example.

**Comment by mollieru** [comment]
@maya good point, though I'm not sure that's what @AccessForAll was getting at. My interpretation was that we should make sure than any form pattern is accompanied by a 'submit' button.

**Comment by maya** [comment]
Sure, also other forms of buttons are `<button type="button">Button</button>` and `<button type="reset">Reset</button>`

**Comment by colinpmacarthur** [comment]
@AccessForAll: Could you help us by clarifying? Are there forms in the pattern library that don't include submit buttons, but should? Or are you suggesting that we need a template for `<button type="submit">Submit</button>` specifically?

Many thanks!

**Comment by maya** [comment]
@colinpmacarthur I believe @AccessForAll means that every form should always include a submit button and not rely on scripting to submit it or activate something.

**Comment by maya** [comment]
We are already including this in our forms. Closing this issue.
