### ISSUE TITLE
[Components/footers] Include a text label above each input box

### ISSUE THREAD

**Issue by AccessForAll** [18F/govt-wide-patternlibrary#172]
* For the sign up section in all of the example footers, include a text label for each box.
      * Without visible text labels, all users may experience cognitive strain when trying to fill in input boxes; however, it's critical to provide persistent labels for people who have cognitive impairments.
      * With text labels that are coded properly, the text helps people with motor impairments to insert their cursors into text boxes.
      * In the HTML5 spec, the W3C says that placeholder text should not be used as a replacement for text labels (http://www.w3.org/TR/html5/forms.html#the-placeholder-attribute).

* See the section "Placeholders that Replace Labels," Nielsen Norman Group:
http://www.nngroup.com/articles/form-design-placeholders/

**Comment by colinpmacarthur** [comment]
We agree! @maya's implementation of the footer removes placeholder text in the fields. Those changes will be visible in the production version of the library soon.

**Comment by mollieru** [comment]
Great suggestion, we've implemented so closing this out for now. Thanks @AccessForAll !
