### ISSUE TITLE
Accordion menu layout fixes needed

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#173]
After a recent merge of [WIP] #159 pull request, the accordion menu layout needs fixing. See image below for before and after reference:

**BEFORE**
![screen shot 2015-07-07 at 9 26 46 am](https://cloud.githubusercontent.com/assets/955558/8546993/b72995a4-2489-11e5-9f2a-7f4a74509e41.png)

**AFTER**
![screen shot 2015-07-07 at 9 19 53 am](https://cloud.githubusercontent.com/assets/955558/8546913/26b51e76-2489-11e5-9cf0-84f19db5f255.png)

**Comment by maya** [comment]
Initial fixes for this here: https://github.com/18F/govt-wide-patternlibrary/pull/175

**Comment by juliaelman** [comment]
Fixed!
