### ISSUE TITLE
Scrolling overlay issue on smaller screen view

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#178]
When viewing the pattern library website < 850px screen width, there is a overlay issue between the header and the main content. See movie below for reference:

![t3z6jwdz7p](https://cloud.githubusercontent.com/assets/955558/8555977/d151c6da-24c1-11e5-920a-00b16ead1324.gif)

**Comment by maya** [comment]
lgtm :+1: 

tiny tiny note....

we are somehow off by 1px in Firefox. Webkit is ok.
![screen shot 2015-07-07 at 2 03 46 pm](https://cloud.githubusercontent.com/assets/5249443/8557290/22fb5494-24b1-11e5-878c-7342015e26ef.png)

**Comment by maya** [comment]
Update: changing `.sidenav { top: 72px; }` (from 73px) in only Firefox seems to resolve this. 

But I don't know if we should be implementing FF-only fixes .But it's also just for the styleguide, so shouldn't be that big of a deal.
