### ISSUE TITLE
[Charts/Graphs] How should we think about designing these?

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#18]
Looking from teams to give us a bit more insight on what components of charts and graphs people are looking for. Like styled out bar charts, line graphs, etc? 

Would be helpful to get guidance on whether this is about visual guidance and/or also building customizeable interfaces, which will require muchmore front end lift.

**Comment by mjovel** [comment]
@mollieru Here are a couple of different examples of data visualizations that currently exist in the FDA world -
* http://www.fda.gov/drugs/developmentapprovalprocess/druginnovation/ucm381397.htm
* http://www.accessdata.fda.gov/scripts/oce/inspections/oce_insp_searching.cfm

I don't think the team would have to reinvent the wheel but possibly just create some standardizations of appearance on existing libraries.

**Comment by cew821** [comment]
Seems to me that getting closer to actual implementation of a data
visualization would be a lot of work, and would add a dependency on some
type of JS visualization library like D3. I also think charting
implementation is often dictated by (or helps dictate) how the back end
data API is structured, increasing the level of difficulty for building
generic components that are usually useful.

However, if done well, I could see how this could be a huge time saver for
a team looking to implement data visualization.

Still, I would be surprised if this level of effort would be worth doing in
the early stages of the project. Definitely I wouldn't take it on unless
you can find a clear customer of the tool who will imement it in a real
app as we build.

**Comment by Scotchester** [comment]
In our breakout group, I was the one who mentioned this item. I agree with @cew821 that offering implementation of it is probably outside the scope of the first release, maybe outside the scope forever, but I think that offering some design best practices advice would be a useful thing to do.

**Comment by cew821** [comment]
Yeah that sounds totally reasonable.

Or maybe just a link to Tufte's Visual Display of Quantitative
Information book 📊📈📉📕

**Comment by Scotchester** [comment]
Also, to call it out explicitly, advice for making charts & graphs **accessible** would be extremely valuable, too.

**Comment by mjovel** [comment]
Agree with with everything @cew821 and @Scotchester have said here

**Comment by amycesal** [comment]
I'm pulling together a design manual issue for CFPB on this: https://github.com/cfpb/design-manual/issues/230 and I put together a data vis style guide for Sunlight Foundation when I worked there: http://sunlightfoundation.com/blog/2014/03/12/datavizguide/

The thing that's nice about the style guide was that it didn't just rely on one platform like tableau or D3, but was broader, then templates for specific programs could be made from it. 

I think as @Scotchester mentioned, accessibility and 508 compliance is a big issue. It looks like census has done some investigation into this: https://fcsm.sites.usa.gov/files/2014/03/AccessibilityCompliance.pdf and there's also color blindness: http://www.dashboardinsight.com/news/news-posts/visualizing-for-the-color-blind.aspx to consider. Also avoiding misleading graphics should be key: https://eagereyes.org/papers/evaluation-of-the-impact-of-visual-embellishments-in-bar-charts

My first take on this has just been to label everything, not rely exclusively on color, and make sure things are legible. My next step is to see what we have, and set some standards across the board. If all platforms can't exactly replicate the standard (hello excel) getting templates as close as possible. 

I'd love to talk more about this at a broader level beyond just CFPB too.

**Comment by mollieru** [comment]
@amycesal this is FANTASTIC!  Thank you thank you for sharing!  We are trying to reuse and build on stuff other folks are doing. Would love to adapt what you're doing for a wider .gov audience!

Can we work together on this?  < v excited >

**Comment by maya** [comment]
I agree with @Scotchester, @cew821, and @mjovel. It's a great idea but don't think we should take this on so early in the project. I think it was only brought up once during the workshop by Scott. Let's keep an eye on it but tackle it later in the project.

**Comment by mollieru** [comment]
Agreed! Esp if CFPB has something in the works, we can dovetail this in
later.
