### ISSUE TITLE
Add content to Accordion component

### ISSUE THREAD

**Issue by carodew** [18F/govt-wide-patternlibrary#184]
Content as follows: 

## Use
Accordions are a list of headers that can be clicked to hide or reveal additional content. 
* They are best used when users only need a few specific pieces of content within a page. 
* Accordion headers can serve as a mini-outline for the content on a page. 
* Accordions can also be useful when information needs to be displayed in a small space.
* One major drawback of accordions is that they increase cognitive load and interaction cost, as users have to make decisions on what headers to click on. 
* Accordions should _not_ be used when visitors need to see most or all of the information on a page, or when there is not enough content to warrant condensing.
* Clicking anywhere on the header (not just on the icon) triggers expansion or collapse of that section.
* Any interactive element within each section should be placed a minimum of 2 mm from the header to avoid accidentally triggering the wrong interaction.

## Accessibility
* Code header areas in the accordion as `<buttons>` so that they are usable with both screen readers and the keyboard.
* All the buttons need to state whether they are expanded or not with the appropriate attribute, either `aria-expanded=’true’` or `aria-expanded=’false’`. 
* Each button has a unique name `aria-controls=’collapsible-#’` that associates the control to the appropriate region by referencing the controlled elements `id`. 
* Each content area has an `aria-hidden` attribute set to either `true` or` false`. When `false`, the element (and all children) are neither visible or perceivable, and assistive technologies will skip this content.

**Comment by juliaelman** [comment]
Fixed #186
