### ISSUE TITLE
Add content to the "Footer" element

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/govt-wide-patternlibrary#185]
Content as follows: 

## Use
Footers serve site visitors who arrive at the bottom of a page without finding what they want. 
Footer links should point to popular content that might answer a visitor’s remaining questions. Links to disclaimers and legal content sometimes need to be in the footer, but try to minimize “disclaimer bloat” wherever possible.
Links do not have to be grouped in the same way they are in the header navigation (especially if the navigation offers many more links than the footer can). 
Include the newsletter sign up if one of your website’s goals is getting visitors to sign up for a newsletter.
Link only to social media your agency updates frequently or uses to communicate with customers. 
Important contact information should be limited to general email or phone numbers, which should be clickable links to dial from a mobile phone. (Physical addresses should live on contact pages users can navigate to from the accordion links). 
			 					
## Accessibility
Code the navigation so that pressing the  tab key moves focus from link to link in the navigation,even when the navigation has collapsed into an accordion.
When collapsed into an accordion, the navigation should also meet the accessibility requirements outlined in the “Accordion” section.

**Comment by maya** [comment]
Done in d6aab53.

**Comment by maya** [comment]
Updated to use bullets in a927ae8.

![screen shot 2015-07-09 at 11 36 01 am](https://cloud.githubusercontent.com/assets/5249443/8603679/a2cdfe78-262e-11e5-8e10-72489e542c80.png)
