### ISSUE TITLE
Create an unstyled button class

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#187]
Opening a tiny issue to reference this comment: https://github.com/18F/govt-wide-patternlibrary/pull/114#issuecomment-120436980 The purpose of this will be to create a way to use `button` and not have any styling associated with it for any state of interaction.

Work started here: https://github.com/18F/govt-wide-patternlibrary/pull/114/files#diff-3dbdc9a9fb01646dec7923eef4a82c33R101

**Comment by colinpmacarthur** [comment]
Added this to the Trello "icebox." Closing out.
