### ISSUE TITLE
Prefix grid-box class 

### ISSUE THREAD

**Issue by maya** [18F/govt-wide-patternlibrary#188]
Prefix the `grid-box` class with `usa` (usa-grid-box), and update all instances throughout the library.

See: https://github.com/18F/govt-wide-patternlibrary/pull/112#discussion_r34313511

**Comment by colinpmacarthur** [comment]
Added this to the Trello "Icebox." Closing out.

**Comment by juliaelman** [comment]
Fixed per #194
