### ISSUE TITLE
What screen sizes are most .gov visitors coming in at?

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#19]
Wishing Charles and/or Leah were on here -- though maybe you know @konklone -- is there deeper data on screen size from DAP beyond what's on analytics.usa.gov?

**Comment by konklone** [comment]
Here's a CSV of screen resolutions from the last 30 days: https://gist.github.com/konklone/45edb36a1a5d71dd330b

**Comment by colinpmacarthur** [comment]
![screen shot 2015-06-10 at 11 38 04 am](https://cloud.githubusercontent.com/assets/2092076/8086802/436fa7fe-0f65-11e5-9aa1-1844ec5c2ce1.png)

Made this quick chart that shows the top 30 screen resolutions in the CSV.

**Comment by cew821** [comment]
This is awesome. Could you do another one sorted by lowest resolution to
highest to get a better visual sense of the volume of people w small
screens?

Also it would be helpful to cut this by desktop tablet and mobile if that's
possible? I think it is cc @konlone I think mobile and tablet are probably
a thing we should anayze separately.

**Comment by konklone** [comment]
FWIW, anyone with DAP access can go and cut up the stats any way they want. :) I didn't use API access -- I just navigated the GA dashboard and clicked the Export to CSV button. If you don't have DAP access yet, you should contact dap@gsa.gov to get it.

**Comment by smarina04** [comment]
Data that is not displayed or available for download on the public dashboard on analytics.usa.gov is for DAP users only and is not for public view. To request access to this data in the DAP application, please send requests to dap@gsa.gov.

**Comment by colinpmacarthur** [comment]
I will pursue getting DAP access so that I can find out the answers to these and other similar questions.

**Comment by cew821** [comment]
I have DAP access already and could pull this, but sounds like we'd need to post it somewhere other than this repo.

**Comment by mollieru** [comment]
@colinpmacarthur has been doing great homework on this. closing out.
