### ISSUE TITLE
Unintended show/hide toggle for footer topics

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/govt-wide-patternlibrary#193]
If you (on a desktop)...
1. shrink your window to mobile width, and
2. then re-expand it to a more regular desktop width
...you can click the "Topic" headers to show/hide what's underneath them.

![](http://g.recordit.co/vsWGpH0i1z.gif)

Proposed functionality: when there's no accordion, clicking the topic header's should not show/hide their child links.

**Comment by juliaelman** [comment]
Fixed with #202
