### ISSUE TITLE
Create coded version of "Contact" block

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#195]
**Description**
We currently only have a placeholder image version of the contact block. This issue to to complete the work to create an actual coded, and responsive, version of the visual design and ux wireframes (see layout below).

**To Do**
- [x] Create html and styles (responsive) based off of current structure
- [x] Run HTML Codesniffer and review for accessibility quality and make any necessary changes
- [x] Submit pull request when code is ready for review
- [x] Once reviewed and merged into staging, run by @angel, @carodew, @colinpmacarthur for final approval
- [x] Iterate/make changes and re-submit PR with any fixes prior to pushing to production

**UX Wireframe**
![contact us_ux_v1](https://cloud.githubusercontent.com/assets/955558/8777696/98eeaf28-2ec7-11e5-9d41-50328cfad721.png)

**Visual Design Wireframe**
![contact-form_ui_v1](https://cloud.githubusercontent.com/assets/103496/8680411/2a31641e-2a2f-11e5-83cc-d93e2783d792.png)

**Comment by maya** [comment]
Completed #218
