### ISSUE TITLE
Create coded version of the "Address" block

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#197]
**Description**
We currently only have a placeholder image version of the address block. This issue to to complete the work to create an actual coded, and responsive, version of the visual design wireframes (see layout below).

**To Do**
- [x] Create html and styles (responsive) based off of current structure
- [x] Run HTML Codesniffer and review for accessibility quality and make any necessary changes
- [x] Submit pull request when code is ready for review
- [x] Once reviewed and merged into staging, run by @angel, @carodew, @colinpmacarthur for final approval
- [x] Iterate/make changes and re-submit PR with any fixes prior to pushing to production

![us_address_form_ui_v1](https://cloud.githubusercontent.com/assets/103496/8680627/95cb8f82-2a30-11e5-84fc-69c9ca1dbfb2.png)

**Comment by angel** [comment]
Here's an updated image with the capitalized ZIP:
![us_address_form_ui_v1](https://cloud.githubusercontent.com/assets/103496/8675346/5d205e16-2a11-11e5-9a20-9c2d2b91032c.png)

**Comment by juliaelman** [comment]
Thanks @angel!

@maya I updated the initial comment with the correct image.

**Comment by juliaelman** [comment]
Completed here: https://github.com/18F/govt-wide-patternlibrary/pull/224
