### ISSUE TITLE
Create basic site architecture for the pattern library

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#21]
For Sprint 2, our focus will be to create a basic site architecture based on the initial wireframes created by the core UX team //cc @carodew @colinpmacarthur 

- [x] Main navigation include
- [x] Side navigation include
- [x] Basic main content structure

**Comment by juliaelman** [comment]
Here are the v1 wireframes for us to get started on the front end work. 

**NOTE** There is another round of changes that are coming up with some feedback from today's overview session. Great work @carodew and @colinpmacarthur!

![gwpl-desktop-wireframes_page_2](https://cloud.githubusercontent.com/assets/955558/8095266/c5e6ae28-0f9a-11e5-98d4-72d427bb0494.png)

**Comment by mjovel** [comment]
Well done!  I really like the use and accessibility content. I was wondering what the use case was for the css and scss tabs within the source tabs? Is it for people to extract those styles and use them within their own set-up? customize them? Most other pattern libraries I have seen have tended to focus on the html. Does listing the css and scss encourage presentational changes leading to increased abandonment of patterns through customization?

**Comment by juliaelman** [comment]
@mjovel thanks for your feedback! I think it will be a matter of testing, iteration and feedback to determine whether or not this approach will cause increased abandonment. //cc @carodew @colinpmacarthur @maya

**Comment by carodew** [comment]
Ditto what @juliaelman said. That's good to know that there seems to be a bigger focus on HTML. We do  plan to do further research and testing into how people want to be able to use/access code – in order to put out something quickly that we can test we are making a few assumptions (and code use is one of those areas). 

On that note, @maya and @juliaelman – since that area is more in question we can talk about things we can do to make it easier to build while still testable. For example, we probably don't need a 'copy' button right off the bat, since people will be able to manually copy/paste if they want to.

**Comment by maya** [comment]
Good point @mjovel. One possibility is we just offer HTML snippets for V1 and allow our users to download the SCSS/CSS files. Then we can continue research the other options. How does this sound? This certainly makes implementation simpler.

**Comment by juliaelman** [comment]
*UPDATE* Here are the v2 wireframes with updates and notes from the team.

![1434055570864](https://cloud.githubusercontent.com/assets/955558/8162628/85e6ce10-134c-11e5-8c99-c152f2611d65.png)

**Comment by maya** [comment]
Also we need to add in the main content area as part of our list.

**Comment by juliaelman** [comment]
@maya added to the list! Also, we might want to piece meal out each one of these things to create smaller PR. I could definitely see each on added as something that could easily be it's own set of code and easily created as a separate PR.

**Comment by carodew** [comment]
Here is the mobile wireframe: 

![gwpl-mobile-wireframe v2](https://cloud.githubusercontent.com/assets/10144074/8239942/1571d372-15cd-11e5-864d-44edc555eb37.png)

**Comment by juliaelman** [comment]
This issue has now been completed with the final merge of #61. :tada:
