### ISSUE TITLE
Feature request: Fancy multi-select

### ISSUE THREAD

**Issue by noahmanger** [18F/govt-wide-patternlibrary#22]
One UI pattern I can see us using on FEC is basically a better multiselect tool that uses checkboxes instead of the typical HTML `<select multiple>` element. 

Refills has a nice one here for reference: http://refills.bourbon.io/#search-tools

See also the way you can filter GitHub issues:

![screen shot 2015-06-10 at 3 10 12 pm](https://cloud.githubusercontent.com/assets/1696495/8095840/574334be-0f86-11e5-99ff-f902c705f851.png)

**Comment by colinpmacarthur** [comment]
(Added to the project's Trello icebox.)

**Comment by nacin** [comment]
Yeah, `<select multiple>` is a terrible user experience, and browsers have done little to make it better, despite new UI/support for various HTML5 elements in the past few years.

Other very commonly used libraries include Chosen and Select2. Many of these solutions, notably, can be used for more than just multi-select. Specifically, what is often called "suggest" or "autocomplete".

I'll then just offer a differentiation there. "autocomplete" implies you are limited to the options being displayed, while "suggest" implies that you can also add an item that does not appear in the list (and it possibly becomes part of the list for the future).

And then you can add "multiple" into the mix, and this gives you a wide variety of use cases.

**Comment by noahmanger** [comment]
I've used Chosen, and while I like the interaction model, I had a couple concerns (and so actually removed it from the FEC project):

- 1. It didn't seem to work with keyboard navigation, so not really accessible
- 2. It was really cludgy to override the CSS and style it in a way that blended in with the site style

**Comment by alex** [comment]
Without suggesting a specific implementation, a select-box-with-autocomplete component would be super valuable.

**Comment by msecret** [comment]
+1 for this idea.

**Comment by Scotchester** [comment]
Related discussion: https://github.com/18F/accessibility/issues/48
