### ISSUE TITLE
Suggestion: Use lower-level heading tag for accordion headers

### ISSUE THREAD

**Issue by rhewitt22** [18F/govt-wide-patternlibrary#221]
Semantically I think the accordion heading lends itself to a heading tag (h3?) rather than a paragraph.  

I'm not sure if this would be making too much of an assumption based on the rest of the content, for example, if your main content had several h3 tags are they roughly equivalent to an accordion heading?

Just a thought that jumped out at me during my user test this afternoon.

Thanks!

**Comment by colinpmacarthur** [comment]
Thanks @rhewitt22 for submitting an issue!

**Comment by msecret** [comment]
I think it depends on the context, meaning that we should ideally build the code so it can be used with any text html tag somebody would want.

**Comment by colinpmacarthur** [comment]
Any thoughts on this one @maya? Shall I put it into the project workflow?

**Comment by maya** [comment]
@colinpmacarthur @rhewitt22 anyone using of the library is free to make this change themselves. Since we don't know the content and use case, it's best left to our users to make the call.

I agree with @msecret.
