### ISSUE TITLE
Question: Would it be feasible to use these patterns as the basis for Angular components?

### ISSUE THREAD

**Issue by rhewitt22** [18F/govt-wide-patternlibrary#223]
Is AngularJS considered inherently in-accessible or could these patterns be used to create a module of Angular ui components? Does the tiny percentage of users with JS disabled preclude us from using Angular in public service?

**Comment by juliaelman** [comment]
@rhewitt22 thanks for you question! Building Angular UI components that are in sync with the pattern library is something we have not discussed yet as a team. It's a good suggestion and will be adding it into our workflow to take into consideration for future development :+1:

**Comment by njohnson** [comment]
I would like to know more about Angular with your templates.   I am a contractor who does front-end development on interactive government sites,  our engineers would like to utilize Angular.   I like the simplicity of it. but am exploring accessibility of angular. At the same time,   I came across the playbook and would like to integrate both Bourbon and Angular.  Our middleware in Spring and Oracle backend.

**Comment by ostranme** [comment]
:+1: for continuing the discussion on Angular. We like the 18F Web Standards and are currently trying to implement into a project of ours. Looping back into the convo above, do you see some kind of Angular UI components being built anytime soon? I'd be nice to have something kind of Angular directive for the web standards.
