### ISSUE TITLE
jQuery bug in IE8

### ISSUE THREAD

**Issue by maya** [18F/govt-wide-patternlibrary#228]
@nickbristow found this bug in IE8 and this breaks the site in IE8.

```
SCRIPT438: Object doesn't support property or method 'addEventListener' 
jquery.min.js, line 2 character 29910
SCRIPT5007: The value of the property '$' is null or undefined, not a Function object 
main.js, line 1 character 1
```

**Comment by juliaelman** [comment]
See screenshot below for reference.

<img width="1202" alt="screen shot 2015-07-27 at 10 28 38 am" src="https://cloud.githubusercontent.com/assets/955558/8908628/2993fc58-344b-11e5-9e7e-e0996bcc2e69.png">
