### ISSUE TITLE
Copy updates for various use and accessibility guidelines

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#237]
There are a few places on the site where some copy updates need to happen. Big thanks to @maya for pointing those out!

**Address form**
- [x] Add politespace note bc it's being used in zip code (addressed via #242)
- [x] We're saying users can type abbreviation for state but we have a dropdown with full names (value is abbreviation but not visible)

**Search bar**
- [x] "The magnifying glass has been shown to be almost universally recognized by users as an indicator of search functionality, and doesn’t need to be paired with the word "Search.""

— but you need to provide screen reader text

**Accordions**
- [x] "Accordions are a list of headers that can be clicked to hide or reveal additional content."

— Are they tho? ours are not headers, they are list items

- [x] "a minimum of 2 mm"

— this is a website, why are we using mm?

**Footers**
- [x] "Important contact information should be limited to general email or phone numbers, which should be clickable links to dial from a mobile phone."

— our phone numbers are not currently clickable

- [x] "Physical addresses should live on contact pages users can navigate to from the accordion links"

— This is not clear. Are we saying that users must provide a link to the contact page in the footer? Just say "footer links"

- [x] "When collapsed into an accordion"

— explicitly state this is only in small screens

**Comment by colinpmacarthur** [comment]
@maya re: 
> "The magnifying glass has been shown to be almost universally recognized by users as an indicator of search functionality, and doesn’t need to be paired with the word "Search."" — but you need to provide screen reader text

Is there a particular place we need to provide the screen reader text?

**Comment by maya** [comment]
Inside the button itself like we are doing.

![screen shot 2015-07-29 at 1 47 07 pm](https://cloud.githubusercontent.com/assets/5249443/8969412/1685496a-35f8-11e5-9ede-79042d7b9eb8.png)

I don't know if there's a better way to state this cc @nickbristow

**Comment by juliaelman** [comment]
Fixed via #250
