### ISSUE TITLE
Create coded version of Labels

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#238]
**Description**
We currently only have a placeholder image version of the labels. This issue to to complete the work to create an actual coded, and responsive, version of the visual design and any UX wireframes (see layout below).

**To Do**
- [x] Create html and styles (responsive) based off of current structure
- [x] Run HTML Codesniffer and review for accessibility quality and make any necessary changes
- [x] Submit pull request when code is ready for review
- [x] Once reviewed and merged into staging, run by @angel / @mollieru and @carodew / @colinpmacarthur for final approval.
- [x] Iterate/make changes and re-submit PR with any fixes prior to pushing to production

**Visual Design**
![labels_ui_v1](https://cloud.githubusercontent.com/assets/955558/8933033/b680f4cc-350e-11e5-9f5f-45d6b06f5726.png)

**Comment by mebates** [comment]
Are labels the same thing as tags?

**Comment by maya** [comment]
@mebates I believe so.
