### ISSUE TITLE
Create coded version of Range Slider

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#244]
**Description**
We currently only have a placeholder image version of the Range slider. This issue is to complete the work to create an actual coded, and responsive, version of the visual design and any UX wireframes (see layout below).

**To Do**
- [x] Create html and styles (responsive) based off of current structure
- [x] Run HTML Codesniffer and review for accessibility quality and make any necessary changes
- [x] Submit pull request when code is ready for review
- [x] Once reviewed and merged into staging, run by @angel / @mollieru and @carodew / @colinpmacarthur for final approval.
- [x] Iterate/make changes and re-submit PR with any fixes prior to pushing to production

**Visual Design**
![range_slider_ui_v1](https://cloud.githubusercontent.com/assets/955558/8937960/996209f6-3529-11e5-86f8-080d5ddbb314.png)

**Comment by juliaelman** [comment]
Switching assignee from @blacktm to @maya, who has begun the work here: https://github.com/18F/govt-wide-patternlibrary/pull/259

**Comment by maya** [comment]
this got a +1 from @nickbristow

**Comment by juliaelman** [comment]
Pending final approval from @angel and/or @mollieru.

**Comment by angel** [comment]
+1!
