### ISSUE TITLE
SSN form should not say "Hide SSN" at the top

### ISSUE THREAD

**Issue by carodew** [18F/govt-wide-patternlibrary#276]
Remove double heading on the SSN input form. Header should be in the same location as other component headers throughout the library and should read "Social Security Number" 

<img width="1242" alt="screen shot 2015-08-10 at 5 04 59 pm" src="https://cloud.githubusercontent.com/assets/10144074/9184284/5a287960-3f82-11e5-8c86-a212cda601fa.png">

**Comment by maya** [comment]
Fixed in #279.
