### ISSUE TITLE
Create ability to have a non-compressed CSS when working locally.

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#28]
@maya brought up the concern of having compressed CSS locally and not easily being able to see the compiled output. There are a few options we can go with here:

1. Add a check in `config.yml` if working locally and turn compression off.
2. Create separate config files for local development vs. staging/production.

**Comment by meiqimichelle** [comment]
I've been hearing about option 2 on many 18F projects. I imagine it depends on your specific project case, but people seem to be making happy noises about the two config solution (or rather, having a second config that overwrites parts of the first as necessary).

**Comment by juliaelman** [comment]
@meiqimichelle right on. can you point us towards an example of another 18F project that does this?

**Comment by msecret** [comment]
You should also look into including good source maps for the compressed CSS. If you could get source maps working correctly for the compressed files in all supported browsers, you may not need to include uncompressed files at all.

**Comment by Scotchester** [comment]
We've found it very hard to get working sourcemaps on production-level CSS, coming from Less source files. The main reason is that sourcemaps are created by the Less compiler, but we run a couple post-processing steps on the CSS (Autoprefixer and LegaCSSy) after that, which ruins the line numbers in the sourcemap. There may be a way around this, but we have tabled that troubleshooting activity for now, as we've begun to investigate PostCSS/cssnext and are hoping that will eliminate the problem.

**Comment by juliaelman** [comment]
Talked with @mbland and we both agreed that creating two separate files for this one data point does not make a ton of sense right now. For now, we'll plan on commenting out the that compression line and see if a more robust solution is needed in the future.

As for creating a way to build a source map, I am opening another issue for this and slating for the Sprint 4 milestone.
