### ISSUE TITLE
Password reset accessibility and design fixes

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#280]
There are a few more requests on changes that need to be made before the finalization of the password reset form. 

**Accessibility fixes:** (from @nickbristow)
- associate the inputs with the instructions with aria-describedby
  - list of requirements for passwords
  - the password strength

**UX/Visual Design fixes:**
- Increase the size of the checkbox a little and the spacing between the checkbox and the text as in the second attachment/cover. See image below:
- Take out the margins of the list elements so they can be closer together. See image below:

![upload_8_11_2015_at_10_46_32_am](https://cloud.githubusercontent.com/assets/955558/9204462/655310bc-402b-11e5-83cc-d65d9124a637.png)

![upload_8_11_2015_at_10_54_58_am](https://cloud.githubusercontent.com/assets/955558/9204461/65518dd2-402b-11e5-864e-c6c1b3c957bf.png)

**Comment by carodew** [comment]
@juliaelman On the Trello convo I suggested to @angel that we need a mock up showing how the line height and margin would work when one of the requirements wrapped to a new line. Are we not doing that?

**Comment by juliaelman** [comment]
@carodew the password reset form has been through two rounds of sprints and would rather @angel and @msecret discuss that height and margin, rather than creating another mock up - thanks!

**Comment by juliaelman** [comment]
Fixed in #282
