### ISSUE TITLE
Add prism.js for code highlighting

### ISSUE THREAD

**Issue by maya** [18F/govt-wide-patternlibrary#31]
http://prismjs.com/

**Comment by juliaelman** [comment]
Thanks for opening this issue and discussion! Curious as to why this is a better solution than using the built-in syntax highlighting Jekyll comes with?

Also, (as mentioned here: https://github.com/18F/govt-wide-patternlibrary/pull/24#issuecomment-112432920) it looks like we'll also need to add the following plugin to make prism.js play nicely with Jekyll https://github.com/gmurphey/jekyll-prism-plugin.

**Comment by juliaelman** [comment]
@maya is this still something that we'd like to add in and change from the current code highlighting we have in place?

**Comment by juliaelman** [comment]
Closing this issue, as we moved forward with using syntax highlighting with pygments. See 5ff09cd7271c26df984670a7faba0d9387be0c10.
