### ISSUE TITLE
Folders for art assets

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#32]
@maya @juliaelman for product testing next week, I'd like to share a few versions of art files of each component for our testing teams to take a peak at. Goal: give folks the ability to be able to get into editable design files of the components. 

Does it make sense to add an _img_ folder at the top level where we load in files for each component (organized like our Drive setup currently) or is there a way to do this? I don't have strong feelings at all as to how this happens -- what do you guys think makes the most sense?

**Comment by juliaelman** [comment]
@mollieru just a few clarification questions:

1. What are the file types you'll want uploaded?
2. Will there be different file types for each component (e.g. PNG, EPS)

//cc @angel too!

**Comment by mollieru** [comment]
Good Qs @juliaelman -- apologies for vagaries!

1. .AI .PNG .EPS -- still deciding on if we'll also have Sketch files ready for this release
2. Yes, one of each of the above for each component.

**Comment by juliaelman** [comment]
Ah! Those will most likely be fairly large files and would prefer them live somewhere outside of this repo.

How about we create another repo for just the artwork? We can then add a submodule in this repo for folks to be able to reference those files here, but only if needed.

**Comment by mollieru** [comment]
Works for me! Great plan. 

:green_button:
