### ISSUE TITLE
[Buttons] Tweak 'focus' states

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#34]
_v1 of components: unbranded basic styling focused on layout, sizing, padding + UX/interaction_

![buttons_ui_v1](https://cloud.githubusercontent.com/assets/3680494/8219377/9d66b2ea-1517-11e5-92ec-5ffbf5b356ca.png)

**Comment by noahmanger** [comment]
Curious what others think on this, but my hunch is that it's important for `:focus` states of buttons to be distinct from `:hover`, or at least be very visually obvious. If you're tabbing through a page and the only indication that a button is focused is a slight darkening, it can be hard to tell. I find outlines more helpful, if a bit unsightly. (I'm sure there's more conclusive research on this)

**Comment by maya** [comment]
I think that's an important point for accessibility. Here are some examples of bolder focus states:

**bright outline**

gov.uk

![screen shot 2015-06-19 at 5 42 17 pm](https://cloud.githubusercontent.com/assets/5249443/8265266/b5711f62-16aa-11e5-8d39-e0ef69863b45.png)

open fec

![screen shot 2015-06-19 at 5 43 15 pm](https://cloud.githubusercontent.com/assets/5249443/8265267/b57371fe-16aa-11e5-8229-0e1837543b6f.png)

**dotted outline**
cfpb

![screen shot 2015-06-19 at 5 45 53 pm](https://cloud.githubusercontent.com/assets/5249443/8265305/814cc5e6-16ab-11e5-8d45-444c50d95345.png)

**box shadow** 
https://open.foia.gov/

![screen shot 2015-06-19 at 5 42 48 pm](https://cloud.githubusercontent.com/assets/5249443/8265307/944fc21a-16ab-11e5-9ee7-a95427ee48d5.png)

**Comment by angel** [comment]
Agreed @noahmanger! Thanks for pointing that out! Will work on a focus state. 

Thanks for the examples @maya!

**Comment by mariamarrero** [comment]
Another example is the focus state on beta.usa.gov. We have implemented the focus for every link. Indeed, needed for accessibility.

![image](https://cloud.githubusercontent.com/assets/6410374/8286061/6103e4be-18d5-11e5-83c9-ce3057ce71d8.png)

**Comment by andrewmaier** [comment]
+1 to @noahmanger

**Comment by jjoteal** [comment]
Curious as to if the yellow used in the focus state meets 508 contrast guidelines? Maybe the 4.5:1 contrast does not apply to focus states?

**Comment by Scotchester** [comment]
The WCAG 2.0 contrast guidelines are specific to the readability of text. I don't believe there are any specific guidelines for the contrast of UI elements like focus outlines.

**Comment by maya** [comment]
If it's a black button on white background the contrast ratio of the yellow focus state will be different for each.

**Comment by carodew** [comment]
Closing this issue and moving into our workflow. Thanks all for the comments!
