### ISSUE TITLE
Style tweaks to [Accordions/Expandables]

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#36]
_v1 of components: unbranded basic styling focused on layout, sizing, padding + UX/interaction_

Leaving this here for feedback:
![accordions_ui_v1](https://cloud.githubusercontent.com/assets/3680494/8219398/da6e6750-1517-11e5-9d74-bdac9657c6e9.png)

**Comment by mebates** [comment]
Our discussion on expandable styles has been extensive: https://github.com/cfpb/design-manual/issues/143

One choice we made is to include the words 'Show/Hide' when the page size is big enough, to improve accessibility.

**Comment by cew821** [comment]
The 20px padding on the content within the accordion feels slightly off to me. I'd like to see it at 15px, or perhaps giving it an extra 5px left and right to match the extra 5px height it's getting now.

**Comment by mollieru** [comment]
Feedback from @jjoteal on icon use in Accordion:

"https://pages.18f.gov/govt-wide-patternlibrary/components/#accordions

Worried that the chevron icon is too close to the dropdown icon.

I've come across this in Ed, where I've had a dropdown menu listed at the first element in an accordion. The result was 2 down-facing chevrons right next to each other. I ended up changing the chevron for the accordion to a plus/minus symbol for expand/collapse to address.

![image](https://cloud.githubusercontent.com/assets/12192706/8501497/0f77ed32-2174-11e5-8545-a8d067b1519f.png) "

**Comment by carodew** [comment]
Moving into our product workflow. Thanks everyone for the comments!
