### ISSUE TITLE
Feedback: [Alerts/Notifications]

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#37]
_v1 of components: unbranded basic styling focused on layout, sizing, padding + UX/interaction_

Leaving this here for feedback:
![alerts_ui_v1](https://cloud.githubusercontent.com/assets/3680494/8219422/00b47a6c-1518-11e5-80b0-473ae5ae8c5f.png)

**Comment by andrewmaier** [comment]
These look good! Are there any mobile-specific styles?

**Comment by Scotchester** [comment]
Nice. Clean and simple!

This is a pretty minor thing, but it might be nice if the icon height matched the height of the heading and first line of description. The icon sorta looks vertically misaligned when there's only a heading and one line of description.

A couple variations you might consider offering:

- A version that has only one type of copy in it (i.e., heading _or_ paragraph, but not both).
- A dismissible alert.

**Comment by andrewmaier** [comment]
Might be nice to color match the icons to the notification (deep green icon for success, etc.)

**Comment by mollieru** [comment]
All helpful feedback, and quite agree. Thanks @andrewmaier + @Scotchester !

cc @angel
