### ISSUE TITLE
[Inputs] Looking for feedback on spacing, styling, etc.

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#38]
_v1 of components: unbranded basic styling focused on layout, sizing, padding + UX/interaction_

[Note: we are also designing form patterns, aka: address field, DOB, login, etc. which will be made up of the follow elements]

Leaving this here for feedback:
![form_elements_ui_v1](https://cloud.githubusercontent.com/assets/3680494/8219463/3c2e1eb8-1518-11e5-8a8a-e3d50afdf46c.png)

**Comment by mebates** [comment]
What type size are you using for the text input labels and the text the user fills in? Is it 16 px, aka H4?

I would make the X and check icons a bit bigger.

**Comment by noahmanger** [comment]
+1 to making the icons bigger, but I find the "x" icon on error confusing. Often times x's next to inputs can be used to clear the input, and that's how I saw it at first. Maybe a "!" would be better?

**Comment by mollieru** [comment]
The inline preview is smaller. Make sure you double click to see actual
size. Once you've done this, still too small?

Also, good advice Noah!

**Comment by carodew** [comment]
@noahmanger I can see your point about the X's potentially being confusing – is that something you've seen play out in user testing? 

I do think the icons could stand to be a bit larger (warning: personal opinion). I could see them being difficult to read for someone who has vision problems.

**Comment by mollieru** [comment]
@angel in putting these elements to work on the form patterns (address, login, etc.), I'm starting to wonder if we might want just slightly larger input fields. Looking @ MyUSCIS, for example, they've got just a bit more breathing room around text. What do you think?

![screen shot 2015-06-22 at 9 54 16 am](https://cloud.githubusercontent.com/assets/3680494/8283257/42b28bac-18c4-11e5-95de-ff7fb6fc6a49.png)
![screen shot 2015-06-22 at 9 53 54 am](https://cloud.githubusercontent.com/assets/3680494/8283258/42beb1c0-18c4-11e5-830b-764e1b325dba.png)

**Comment by mollieru** [comment]
@angel also, I think we should adopt the asterix for required field, vs. writing the word ``required`` -- sometimes the field labels are long and run into the word. (See above)

**Comment by carodew** [comment]
A couple of things – 

Marking the Optional fields vs the required fields has been shown in research to encourage more user completion of forms. Also, hopefully as one is designing their forms one is taking care to make sure there aren't very many 'optional' fields anyway, meaning that fewer fields will need labels. 

Writing out the word tends to be more user friendly and create less confusion. I've found that icons are more easily misinterpreted than just spelling out the words, even if it means the UI isn't as minimal as we design-oriented folks would like. So I would vote for keeping the words spelled out and coming up with an alternative layout for when labels are too long. 

See: http://www.lukew.com/ff/entry.asp?725
And: http://uxmovement.com/forms/why-users-fill-out-less-if-you-mark-required-fields/

**Comment by colinpmacarthur** [comment]
+1 to Carolyn, especially on writing out the words. I think asterisks seem
like a common convention, but I've seen them not get noticed / used by less
experienced users in usability tests at other agencies.

**Comment by mollieru** [comment]
ok good advice you two! We will work around the design constraint and find a good solution!

**Comment by noahmanger** [comment]
@carodew I haven't tested it myself, no. But then again, I haven't needed to.

**Comment by andrewmaier** [comment]
I'm personally not a huge fan of pixel measurements/requirements as it sets an unrealistic bar. I would prefer something in `em`'s (that is, relative to the font size). Check the screenshot for three differently sized buttons (the "remove" button is being hovered). I made the size of the buttons match the font-size of the text that the button appears next to.

![screen shot 2015-06-22 at 4 04 52 pm](https://cloud.githubusercontent.com/assets/2970/8291574/6d9a866a-18f8-11e5-8857-a06e21fb9cb3.png)

It's also really important to me that this be implement this in a modular/"progressively enhanced" way.  FilamentGroup has a number of plugins that they use to enhance forms and I've reliably customized them on client-facing work. See http://www.filamentgroup.com/code/ (esp. the code links under the "Accessible form elements" heading)

**Comment by mollieru** [comment]
@andrewmaier great suggestions! #82 is an issue already open related to `em` styling. Adding this suggestion to that issue as reference.

Moving your suggestion about 'progressive enhancement' to a new issue.

**Comment by Scotchester** [comment]
I would caution you about the error/success messaging pattern of having the icon appear to the right of the field. We set a similar standard, but in practice found that it was often difficult to pull off – specifically, any time you want to have two fields sitting next to each other horizontally. Consider: How would this work in your example address field if the user neglected to fill out the required City field?

---

> "I'm starting to wonder if we might want just slightly larger input fields."

Nah, I don't think so. The USCIS ones feel like they have _too_ much space, to my eyes. The VA ones look about the same as your proposed designs, to me, or even slightly less, and they feel very comfortable to me.

---

Last, maybe it's just me, but the labels set in bold feel too heavy to me.

**Comment by maya** [comment]
It may be harder to implement error messages to the right of the field. I'd recommend an approach that places them below the field. It also gives a more consistent experience in smaller screens.

This is how gov.uk does it:
<img width="411" alt="screen shot 2015-07-04 at 3 47 01 pm" src="https://cloud.githubusercontent.com/assets/5249443/8526408/715e3f1c-23bb-11e5-8fb3-5698a57e5f5f.png">

On http://app.homebasefix.com/, we also used error messages between the label and field.
<img width="754" alt="screen shot 2015-07-04 at 3 17 40 pm" src="https://cloud.githubusercontent.com/assets/5249443/8526437/9b819a46-23bb-11e5-874c-56268d6e5bb0.png">

**Comment by maya** [comment]
@Scotchester Re: bold labels - We're only using two weights for fonts, normal and bold. Are you suggesting to see labels in a normal font weight?

**Comment by Scotchester** [comment]
Yes, I'd like to see them at Normal and see if they work okay that way.

**Comment by andrewmaier** [comment]
@maya +1 to normal fonts.

**Comment by carodew** [comment]
I would just want to be sure there is some type of visual cue for the alerts other than the color red so that they can stand out even for the color blind. In @maya's examples, the top image has a vertical red bar on the left margin that draws attention. It could also be an icon or a background color.

**Comment by maya** [comment]
@carodew I just realized we _are_ recommending this pattern for Sign In error messages. Any idea why we are recommending two different error message patterns? How will people know when to use one or the other?

![screen shot 2015-07-07 at 1 51 17 pm](https://cloud.githubusercontent.com/assets/5249443/8556973/3582e0c0-24af-11e5-86b4-d2b4c528a642.png)

![screen shot 2015-07-07 at 1 52 57 pm](https://cloud.githubusercontent.com/assets/5249443/8556994/57880cc2-24af-11e5-8094-0120b91700e5.png)

**Comment by carodew** [comment]
There are generally two different types of alerts – one is the top-of-page alert that says what is wrong, and the other is the in-line alert that appears alongside (or below) the problematic form field. You can use both. It's hard to tell that the example on the sign in screen is intended to be the former, but it is. So the alert in question (in terms of positioning to the left or below or between the label and field) is only the inline-alert. On very short forms, including both may be too much, but on longer forms it tends to be helpful to have both. See http://static.lukew.com/webforms_lukew.pdf starting on slide 113.

**Comment by maya** [comment]
Related: https://github.com/18F/govt-wide-patternlibrary/issues/169

**Comment by mollieru** [comment]
Comment from @AccessForAll from https://github.com/18F/govt-wide-patternlibrary/issues/169

"* The location is problematic for people who use screen magnification software, people who have cognitive impairments, and people who are using small screens.

* Reconsider placing the error text above the input box."

**Comment by maya** [comment]
@andrewmaier @Scotchester Here are input labels in bold and normal weights:

Bold:

<img width="536" alt="screen shot 2015-07-08 at 6 44 31 pm" src="https://cloud.githubusercontent.com/assets/5249443/8586249/68bc3c50-25a1-11e5-9b4f-35a77d845f1e.png">


Normal:

<img width="534" alt="screen shot 2015-07-08 at 6 44 22 pm" src="https://cloud.githubusercontent.com/assets/5249443/8586250/6e02a780-25a1-11e5-812a-249a4a3388ef.png">

**Comment by Scotchester** [comment]
I feel like they're friendlier in the normal weight, but that's just my opinion :)

**Comment by andrewmaier** [comment]
Normal++

**Comment by colinpmacarthur** [comment]
Thanks for all the suggestions, everyone!

All the suggestions on this issue have either been:
* responded to,
* split into separate issues, or
* added to our project's workflow for possible inclusion/addressing later.

Feel free to open new, separate issues for more feedback.

**Comment by andrewmaier** [comment]
@colinpmacarthur @maya In more accessibility-related news: you shouldn't communicate state by color alone. Error/Success states should have icons or some kind of wording to explain that their data is valid.

**Comment by maya** [comment]
@andrewmaier Agree! We'll be working on error messages next sprint :)
