### ISSUE TITLE
Pattern [Footer]

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#45]
_v1 of components: unbranded basic styling focused on layout, sizing, padding + UX/interaction_

These are in-progress -- still need to refine padding and spacing, but @angel would love general feedback on font size + layout. (cc @colinpmacarthur )

(Doing desktop first, then will add in mobile)
![footer_desktop_ui_v1](https://cloud.githubusercontent.com/assets/3680494/8236126/2d35d972-15b4-11e5-82d5-bddb8920dee8.png)

**Comment by angel** [comment]
These look good to me. I would reduce the padding between the Primary Nav heading and the secondary link to be the same distance as the secondary links.

**Comment by mollieru** [comment]
Good tip. @angel how's this looking? 
![screen shot 2015-06-19 at 12 34 19 pm](https://cloud.githubusercontent.com/assets/3680494/8257940/21b0e92c-167f-11e5-99ed-6da771e1a1e4.png)

**Comment by angel** [comment]
Looks phat to me! :+1:

**Comment by mollieru** [comment]
Updated fat, medium + skinny desktop footers.
![footer_desktop_ui_v1-forgithub](https://cloud.githubusercontent.com/assets/3680494/8261216/bd524e40-1696-11e5-8889-360a77f750bb.png)

**Comment by mollieru** [comment]
Here's v1 of mobile footers:
![footer_mobile_ui_v1](https://cloud.githubusercontent.com/assets/3680494/8283486/9efda8a0-18c5-11e5-99c8-776cfaa2ed5a.png)
