### ISSUE TITLE
CSS class naming

### ISSUE THREAD

**Issue by jonraedeke** [18F/govt-wide-patternlibrary#47]
It would be great to get a consensus on class naming in the markup. I'm struggling with this a bit myself. Even though it's ugly, I am growing fond of the [BEM style](https://css-tricks.com/bem-101/), because it:

* avoids unnecessary cascading that can bleed into other components in a big system
* makes it easy to know the dependencies of a particular element
* makes it easy to find the style in the file structure if you use the component name for the file name
* encourages good practices of building in a modular way

``` css
/* Block component */
.btn {}

/* Element that depends upon the block */ 
.btn__price {}

/* Modifier that changes the style of the block */
.btn--orange {} 
.btn--big {}
```

## Exceptions
* How deep should this go? I feel like it should only go one element deep. If it needs to go deeper, you might need another 'block' or component.
* General helper classes like .left should still be used when possible.

Would love to get opinions on this.

**Comment by mollieru** [comment]
@maya has been thinking a lot about this!

**Comment by mjovel** [comment]
@jonraedeke Last I heard they were strongly considering BEM. Not sure if they have gone further than this @maya could probably provide a more definitive answer here.

**Comment by maya** [comment]
@mjovel @jonraedeke yes, I think we are leaning towards a BEM or modified BEM approach. 

This is the current 18F "modified BEM" methodology:

The 18F recommendation for a naming methodology is a modified version of BEM. It still uses blocks, sections within blocks and modifiers, but doesn’t use as long a syntax.

```
.accordion
.accordion-item
.accordion-item-selected

.nav_bar
.nav_bar-link
.nav_bar-link-clicked
```

@msecret and @meiqimichelle who are leading the frontend guild have put a lot of thought into this as well. 

Would love to hear what you think about those approaches or where exceptions should be made.

**Comment by jonraedeke** [comment]
I really like that syntax.

**Comment by mjovel** [comment]
@maya I think the modified BEM approach you reference sounds good to me.

**Comment by juliaelman** [comment]
Great to get everyone's feedback, ideas and thoughts! +1 Sounds like we are all on the same page in regards to a modified BEM approach and we'll take this all into consideration as we move forward.
