### ISSUE TITLE
Library structure and packaging

### ISSUE THREAD

**Issue by contolini** [18F/govt-wide-patternlibrary#48]
Hi friends! I'm pumped to see this thing start to take shape. Y'all are killing it.

Have you given any thought to how the library will be structured? i.e. Will it be monolithic, similar to how Bootstrap and Foundation work, with all components in a single repo and a script that concats all source files? Or will each component have its own repo a la Basscss, Semantic UI, Topcoat?

In the same vein, how will components be packaged for consumption? I assume you'll generate a *name-of-library*.css file for users to download but do you also plan on publishing it to package registries like npm and Bower? It'd be ideal if each individual component was published separately, so that if I just want your button styles, I'm not forced to install your entire framework. Semantic UI does a [really good job](https://github.com/Semantic-Org/UI-Button/#to-install-with-bower) in this regard.

I apologize if these topics are premature/overwhelming/have already been discussed. I'm just *really* excited to see this library happen.

**Comment by juliaelman** [comment]
@contolini your excitement is welcome and we appreciate your feedback, thoughts and ideas! We have definitely considered many of the things you are pointing out, especially your point about wanting each individual component to be published separately. +1 thanks again!
