### ISSUE TITLE
What should our url be?

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#5]
Opening this issue to brainstorm ideas on what the url for the pattern library should be. Please feel free to add any ideas you have in the comments:

- uspatternlibrary.*.gov
- govtwidepatternlibrary.*.gov
- usgovtpatternlibary.*.gov

**Comment by juliaelman** [comment]
+1 usapatternlibrary.*.gov sounds great - thanks @maya!

**Comment by mollieru** [comment]
Should we consider living off of USA.gov?

**Comment by maya** [comment]
so like USA.gov/patternlibrary ?

**Comment by mollieru** [comment]
Ya.
Context = growing interest in reducing the # of unique top level .gov
domains in the world

**Comment by juliaelman** [comment]
@mollieru +1 I think for now we were thinking of getting something up quickly and a subdomain pretty simple/straight forward. We should definitely re-think domain names as we get further along in the project.

**Comment by mollieru** [comment]
Sounds good! Works for me!

--
Mollie Ruskin
503.928.2988
mollieru@gmail.com

**Comment by juliaelman** [comment]
Re-opening this issue! I had originally opened it so that we could move forward with a [simple subdomain](https://github.com/18F/govt-wide-patternlibrary/issues/5#issuecomment-108479824) to work off of our Cloud Foundry. Re-adjusting focus towards away from CF and opening back up for a larger discussion on what our url should be :raised_hands: 

This might also be effected by the outcome of #10 too.

**Comment by cew821** [comment]
I feel like there are a lot "pan-Digital Service" products/content pieces that would benefit from a top-level domain, possibly a new one (but I don't know what that is).

`patternlibrary.digitalservice.gov`
`playbook.digitalservice.gov`
`jobs.digitalservice.gov`
`guides.digitalservice.gov`
`vadigitalservice.gov`
`ssa.digitalservice.gov`

You get the idea... I feel like this style pattern library, the Playbook, the TechFAR, the 18F Guides, the job application, and a few other things want to be grouped under one home.

**Comment by mollieru** [comment]
@cew821 I like what you're after. Do you know if/where convos are on the digitalservice.gov domain? 

Seperate thread, starting to think about the branding of the 'library' product (vs the components), I'm wondering, based on the early user feedback from @carodew and Colin shared, if we should steer away from the term 'pattern library' and think instead about 'web design standards' or 'web design guides' -- which would include, principles, a library of components and patterns, and a brand suite. 

So maybe like:
'<webdesignguide.digitalservice.gov>'

(This is sort of the CFPB branding approach).

**Comment by nacin** [comment]
Pending ongoing branding and collaboration efforts, it's possible it ends up being digital.gov. Something super simple like design.digital.gov could be interesting. Just throwing it out there.

I'd probably piggyback on usa.gov for the moment. designguide.usa.gov? I don't think "web" is needed here.

**Comment by mollieru** [comment]
It's important to keep in mind 'design' means more than one thing. I'm
increasingly into 'web design standard' or 'web design guide'.

**Comment by maya** [comment]
@mollieru Re: 'web design standard' - I wonder what the association with the Web Standards movement from the 1990s + early 2000s would imply https://en.wikipedia.org/wiki/Designing_with_Web_Standards

**Comment by mariamarrero** [comment]
Just catching up with all the messages. Great feedback!

USA.gov is open to be the initial home for this design guide. I like the initial idea @mollieru suggested:  USA.gov/patternlibrary. We could even pilot the guides in USA.gov, so users can see the guides applied in the same place.

**Comment by jpyuda** [comment]
USA.gov seems like a sensible place.

But I'd suggest somesubdomain.usa.gov, both because it's a little easier to administrate that way, and the content is probably not of interest to most of usa.gov's audience. This is for insiders/devs, not users.

**Comment by mollieru** [comment]
Sounds great to me! @jpyuda + @mariamarrero I'm *super* excited about this living on USA.gov -- thank you for the invitation :) 

Also into somethingrelevant.usa.gov -- working on what that 'something' now.

**Comment by mariamarrero** [comment]
Thinking about what @jpyuda mentioned on this content being more towards insiders/devs, not users. USA.gov has a "Developers" page and just wanted to share that as another possible place. In our current site here is the page: http://www.usa.gov/About/developer-resources/developers.shtml, but in the future (starting next week - when beta.usa.gov becomes our only site) all the developers' content will leave here: https://beta.usa.gov/developer. Will that be another possible home for this content? Thoughts?

**Comment by jpyuda** [comment]
I think I'd prefer to keep it at a subdomain (at least for now) where we can update it more quickly, etc.

**Comment by mariamarrero** [comment]
Sounds good and makes sense. Just wanted to put out there possible places :)

**Comment by cew821** [comment]
If we do wind up putting this in usa.gov, I think that implies that other similar products should be put there? Things like the Digital Services Playbook, 18F's Guides, and other things related to helping agencies deliver better services? 

I'm actually ok with that, but I do think it represents a conscious choice, and one that we should follow for other similar products like the Playbook, Guides, etc.

**Comment by jpyuda** [comment]
I don't think it implies that at all.

**Comment by cew821** [comment]
Interesting! I'd love to understand better. Is that because you think there aren't similarities between the products, or because you think the choice of URL doesn't really matter? Or some other reason?

My intuition was that it would be nice for similar types of resources to be grouped together, but definitely open to other reasoning!

**Comment by jpyuda** [comment]
Well, the audiences are often pretty different. The playbook is for CIOs and program managers. The UI library is for designers and devs.

18F Guides, on the other hand, will probably be a mix of a bunch of different things. But it seems like a case where the 18F "brand" may be an important part of the product.

**Comment by carodew** [comment]
Seems like this conversation has run it's course, I'm moving this into our product backlog for the team to tackle. Thanks everyone for your comments!
