### ISSUE TITLE
Tweak placement of <h2> Titles after clicking corresponding sidenav item

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#63]
Small visual tweak. Noticing that upon clicking secondary Nav links in the sidebar, the corresponding `<h2>` title lands high up on the page:

![screen shot 2015-06-23 at 12 56 27 pm](https://cloud.githubusercontent.com/assets/3680494/8312212/63184d88-19a9-11e5-98e7-9a7c1c3e0051.png)

Recommend aligning these `<h2>`s so that on page load, they are in line w top of the sidebar nav text like this:

![screen shot 2015-06-23 at 12 57 01 pm](https://cloud.githubusercontent.com/assets/3680494/8312214/663dab3e-19a9-11e5-9463-76908b7ab92f.png)

**Comment by maya** [comment]
I just want to document that this appears to be a webkit bug, and works fine in Firefox, cc @juliaelman

**Comment by maya** [comment]
@mollieru this is fixed in: https://github.com/18F/govt-wide-patternlibrary/pull/70

This is what it looks like:

 ![heading-fix](https://cloud.githubusercontent.com/assets/5249443/8316871/853bc73c-19ae-11e5-8161-0b1f1616e140.png)

**Comment by mollieru** [comment]
Thanks @maya ! Lookin good.
