### ISSUE TITLE
Add smooth scrolling to sidebar items

### ISSUE THREAD

**Issue by maya** [18F/govt-wide-patternlibrary#72]
We currently jump directly to the components after clicking its link. It may be nice to use a smooth scrolling effect so users have context of where they're navigating to within the page.

**Comment by maya** [comment]
This is done in this PR: https://github.com/18F/govt-wide-patternlibrary/pull/71

**Comment by carodew** [comment]
+1 to smooth scrolling

**Comment by maya** [comment]
Resolved in https://github.com/18F/govt-wide-patternlibrary/pull/71
