### ISSUE TITLE
Update sidenav links to reflect split out components previously called 'Forms'

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#73]
We broke out the individual bits of 'Form Elements' and 'Form Patterns' into their own sections. The sidebar links currently don't reflect this (though the page content does).  Update sidebar nav links as follows (new links in *italics*):

ELEMENTS
> Buttons
> *Text input*
> *Checkboxes*
> *Radio Buttons*
> *Labels*
> *Dropdowns*
> Tables

COMPONENTS
> Accordions
> Alerts
> Footers
> *Address Form*
> *Name Input Fields*
> *SSN Input Fields*
> *Sign in Form*
> *Password Reset Form*
> *Contact Form*
> *Date select*
> Navigation + Header
> Search Bar
> Search Results

(I know the alphabetizing will re-order this, that's totally fine)

NOTE: I suspect this is all is subject to change based on usability testing later this week. The goal here is just to make sure we have findable links to all of the sections of the site.

**Comment by carodew** [comment]
Per Slack discussion, we agreed that for now we'll change the link that says "Forms" under the Elements grouping will be changed to instead read "Inputs," and the link that says "Forms" under the Components grouping will be changed to read "Form Blocks" (excluding the punctuation). We'll then decide on further changes to the nav based on our sprint 3 user testing.

**Comment by mollieru** [comment]
+1!

**Comment by maya** [comment]
Completed in https://github.com/18F/govt-wide-patternlibrary/pull/69
