### ISSUE TITLE
Load [Dropdowns] to [Elements>Inputs]

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#74]
Just noticed the image is missing.  It's here in drive:

https://drive.google.com/thumbnail?id=0B4cLTFDoVvuDUnZIc1lyWEpmdTA&authuser=0&v=1435075654807&sz=w1294-h877

**Comment by maya** [comment]
@mollieru please see https://github.com/18F/govt-wide-patternlibrary/issues/76#issuecomment-114963532 and let me know if you have any questions.

**Comment by mollieru** [comment]
Not seeing 'Dropdown' in your PR hitlist @maya

**Comment by maya** [comment]
Just added it in the checklist, it was included in the source files. Closing this issue.
