### ISSUE TITLE
Add 'under construction' bar to top of the site

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#75]
Suggest adding an 'in progress' note w 'us govt website' bar. 

Suggest repurposing the FOIA team's approach, with the following text:

![screen shot 2015-06-24 at 12 36 08 pm](https://cloud.githubusercontent.com/assets/3680494/8335750/9452c288-1a6d-11e5-922a-36917f27b9fe.png)

BAR
*[US flag]  An official website of the U.S. Government. This website is in development. Learn more* 

DROPDOWN
*This site is in development. Tell us what you think!*

*You are visiting the first release of site designed to create web patterns and element styles for use across federal government digital materials. This release includes wireframe mockups of UI elements.  Your feedback is important to us as we build this site and we encourage you to contribute your input at https://github.com/18F/govt-wide-patternlibrary/issues*

*This project is a partnership of the US Digital Service and 18F. If you'd like to learn more, please email govtwidepatternlibrary@gsa.gov.*

**Comment by carodew** [comment]
I asked about the "An official website of the US gov" bar in the design channel in Slack and there didn't seem to be consensus about whether or not it was useful to users. That being said, I'm not against adding it. 

I would suggest the following changes to the language: 

BAR: 

This site is in [alpha](https://18f.gsa.gov/dashboard/stages/#alpha).

Reasoning: "Learn more" is vague language out of context. Potentially could link the entire phrase "This site is in alpha" as well. 

Have you thought about how it should appear in the mobile view? Does the FOIA site provide a precedent?

**Comment by juliaelman** [comment]
@carodew for pulse, this is how we did the layout for mobile and can do something similar for the pattern library website too:

![screen shot 2015-06-24 at 1 22 36 pm](https://cloud.githubusercontent.com/assets/955558/8336606/b4b3d142-1a73-11e5-9e5f-b485f31d7f03.png)

**Comment by carodew** [comment]
Can we add a :construction: ?? 

Kidding, kidding.

**Comment by carodew** [comment]
I worry about the dropdown menu chewing up a lot of real estate on the mobile screen, although I like the ability to point people to how to provide feedback. 

I like both the FOIA and Pulse models of the top bar.

**Comment by juliaelman** [comment]
@carodew haha! Nice use of emoji.

I'd like to separate out the top bar from the feedback for now and get that implemented first. Is everyone cool with me moving forward for a pull request on the top bar?

**Comment by mollieru** [comment]
sounds good to me! 

@carodew what do you think about taking the content from the dropdown and adding it to the 'about' page for now?

**Comment by mollieru** [comment]
(also +1 on your point about the 'Learn more' language)
