### ISSUE TITLE
Add [Date Picker] to [Components]

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#76]
QA reviewed caught that this file didn't make it onto the sidebar and the image isn't loaded. Image file is here in Drive: https://drive.google.com/open?id=0B4cLTFDoVvuDWUV1cTJsQnctVmM&authuser=0

**Comment by maya** [comment]
@mollieru it's already been added to this PR, we just have not merged yet. Please refer to this PR for missing components bc I think the ones previously mentioned are already here. https://github.com/18F/govt-wide-patternlibrary/commit/8aaef3768aba3c69392c779ae1feacb8019efe2f

**Comment by mollieru** [comment]
roger! sorry.

**Comment by juliaelman** [comment]
Fixed in #69
