### ISSUE TITLE
Update [Search results] UI mobile pagination to UX team revised wireframe

### ISSUE THREAD

**Issue by angel** [18F/govt-wide-patternlibrary#77]
![mobile search results](https://cloud.githubusercontent.com/assets/103496/8339349/c4fdaa94-1a84-11e5-8300-420df004d4a2.png)

Current Mock:
![image](https://cloud.githubusercontent.com/assets/103496/8339380/fb83a848-1a84-11e5-8351-7aa7f647da52.png)

**Comment by mollieru** [comment]
@angel you've updated this yea? I think you can close this for now.

**Comment by mjovel** [comment]
@angel @mollieru I did not see the search results layout under the designs for feedback.  I have two small things for consideration. Would you like me to submit them as issues? or via some other mechanism?

**Comment by carodew** [comment]
I realize the question was not directed at me, but @mjovel, do you want to post your comments here and we can decide if they should be separate issues? The team can always move them around if need be. I'm interested to hear your ideas.

**Comment by mollieru** [comment]
@mjovel go ahead and create new issues -- this was for an internal task, so I'll close it out. (in general, @carodew 's right -- you can always plop ideas in and we'll move it around if need be).
