### ISSUE TITLE
Integrate 18F College Choice form styleguide

### ISSUE THREAD

**Issue by ErieMeyer** [18F/govt-wide-patternlibrary#78]
Hi all,

@meiqimichelle made another styleguide for a project we're working on here: https://github.com/18F/college-choice/tree/form-styleguide/styleguide

Could you integrate it, or point us to where we should be contributing it?

Thank you!

**Comment by maya** [comment]
@ErieMeyer is this project private? I'm seeing a 404 page when I click that link.

**Comment by mollieru** [comment]
Would VERY much like for this to feed into our work however possible.  Will be sharing a link to the first release of our prototype shortly with instructions for how folks can feed in. @jjoteal and I have been in touch about getting her team's feedback on what we're doing...and hopefully there will be elements of this draft which can be repurposed for the college choice project!

**Comment by mollieru** [comment]
To second what @maya said -- we can't access that link. Can we get access and/or screenshots?

**Comment by juliaelman** [comment]
Updated issue to be more specific as to what style guide @ErieMeyer is referring to.

**Comment by meiqimichelle** [comment]
Hey all! I'm already in convo with @juliaelman about this, it will get fed back. It is only 508-compliant form elements -- so, more properly called a 'form coding guide' perhaps?

**Comment by meiqimichelle** [comment]
Ah, which I see Julia already updated the title to be more specific :) Yays.

**Comment by juliaelman** [comment]
@meiqimichelle :+1: team front end FTW!

**Comment by mollieru** [comment]
Sounds like this is well underway, so closing out for now.
