### ISSUE TITLE
Looking for feedback on v1 Look + Feel Mood Boards

### ISSUE THREAD

**Issue by angel** [18F/govt-wide-patternlibrary#80]
Hey All!

Here are 3 mood boards that we have come up with for the look and feel of the the pattern library. I would love everyone's feedback and thoughts on them. Thanks for your help!

# 1. Modern American 
Bright saturated colors, blocks of color, wider bold sans-serif fonts for headings

![mood-board-modern-american](https://cloud.githubusercontent.com/assets/103496/8342318/2c6cf018-1a99-11e5-9caa-27aa2b82f0de.png)

# 2. Inspiring and Empowering
Colors rooted in old American propaganda, papers, and stamps, more airy feel, bold condensed sans-serif or serif fonts for headings

![mood-board-inspiring-empowering](https://cloud.githubusercontent.com/assets/103496/8342313/28c1454a-1a99-11e5-9838-d3fd54fc29a5.png)

# 3. Clean and Classic
Classic colors, more minimalist feel, traditional serif fonts for headings and body

![mood-board-clean-classic](https://cloud.githubusercontent.com/assets/103496/8342312/274985ce-1a99-11e5-8083-a3f59bc658f4.png)

Don't forget to click on the image to see a larger version.

**Comment by cew821** [comment]
I would love to see some more of the mood board examples come from services, instead of content sites. It's a bit hard to tell how the various proposals would impact something like a form or other transaction-oriented interaction from these mood boards.

That said, I think I have a slight preference for the first example, then 3, then 2.

**Comment by mebates** [comment]
@angel This is the look and feel of the pattern library itself, right? Not the standards we're hoping other sites will use. (I remember @mollieru talking about providing a few options for that. Though it would make sense if this look/feel were one option).  If so, I prefer the modern american look. Just be super-aware of 508 compliant type with thin fonts and light backgrounds. I would look at the 508 type/color field relationships before committing to colors.

**Comment by angel** [comment]
@mebates yes, the latter! An option for the look and feel for the standards themselves. We will definitely be sure to pick 508 compliant colors as we narrow and refine the look and feel. If you have any favorite 508 resources please let me know! Thanks for your feedback!

**Comment by CaliforniaKara** [comment]
Love how varied the different mood boards are! I dig the bold, confident nature of the fonts in #1, the aspirational, welcoming color scheme in #2, and the approachable nature of the images in #3.

If you think it'll help, here are the style tiles from PIF1 MyGov project: http://beta.presidentialinnovation.org/mygov/2012/11/05/style-tiles/ They're based on research done at Library of Congress and National Archives we did on how the federal government historically communicated with the people, and vice versa. You can click the image to see all 4 style tiles we created (the first 3, then the final).

**Comment by mollieru** [comment]
Rad, thank you for sharing @CaliforniaKara!

**Comment by mollieru** [comment]
Transferring feedback from @mariamarrero from https://github.com/18F/govt-wide-patternlibrary/issues/127

"The mood boards contain very neat color palettes. Is the look and feel chosen only for the library or could these be choices for agencies to use? Some agencies may use colors that are similar, but not exactly, to meet internal color contrast requirements.

If this helps, a great color contrast tool that I always use to meet contrast requirements for foreground and backgrounds colors (text and graphics) is http://webaim.org/resources/contrastchecker/.

My favorite is the Modern American :) "

**Comment by Scotchester** [comment]
The Modern American mood board resonates most with me right away, but it's more of an emotional response than a logical one. I do like the mid-century propaganda art source images for the inspiring and empowering board, but am not sure that it translates very well into a contemporary web design language.

:+1: to @cew821's comment about wanting to see some more examples of services/transactions in these boards.

### Re: Color contrast

While checking individual color pairs is great, I heartily recommend [this whole-palette contrast evaluator](http://accessibility.oit.ncsu.edu/tools/color-contrast/accessible-color-palette.php?&colors=2cb34a,addc91,dbedd4,101820,43484e,75787b,919395,babbbd,e3e4e5,f1f2f2,f8f8f8,d12124,da6750,e8a091,f6d9d3,ff9e1b,ffb149,ffce8d,ffecd1,796e65,948b84,bcb6b2,e4e2e0,002d72,33578e,7f96b8,ccd5e3,0072ce,328ed8,7fb8e6,cce3f5,005e5d,337e7d,7faeae,ccdfdf,ffffff&level=AA) tool, which lets you input all of the colors in your palette and evaluate each one against all of the others for acceptable contrast. The linked example shows how CFPB's current palette stacks up.

**Comment by maya** [comment]
@Scotchester what a handy tool! Does CFPB follow AA (4.5:1) or AAA (7:1) color contrast ratios? What are we supporting?

**Comment by Scotchester** [comment]
CFPB follows AA. I think that's what I'd suggest for this project, too. AAA
is really hard!

**Comment by carodew** [comment]
Thanks for the feedback!
