### ISSUE TITLE
Feedback: Consider using ems or rems instead of pixel values for spacing, line-height etc

### ISSUE THREAD

**Issue by dannychapman** [18F/govt-wide-patternlibrary#82]
This would be great from a font-sizing standpoint for general interoperability. I realize that browser zoom does make this less relevant, but there are still times people set their font size bigger, without zooming the overall viewport.

**Comment by Scotchester** [comment]
@dannychapman I believe that they [already are](https://github.com/18F/govt-wide-patternlibrary/blob/18f-pages-staging/assets/_scss/core/_variables.scss). I suspect pixel values are being used in the copy/diagrams as a convenience. It's easier to get your head around the computed size than to think in (r)ems.

**Comment by mollieru** [comment]
Totally agree. Pro ems once we move into code. 

Do you guys think we should only give ems or both ems + pixels?

**Comment by mollieru** [comment]
From @andrewmaier issue #38 :

I'm personally not a huge fan of pixel measurements/requirements as it sets an unrealistic bar. I would prefer something in `em`'s (that is, relative to the font size). This is what I'm doing on the Airforce (SBIR-EZ) project: the screenshot shows three differently sized buttons (the "remove" button is being hovered). I made the size of the buttons match the font-size of the text that the button appears next to.

![screen shot 2015-06-22 at 4 04 52 pm](https://cloud.githubusercontent.com/assets/2970/8291574/6d9a866a-18f8-11e5-8857-a06e21fb9cb3.png)

**Comment by maya** [comment]
@dannychapman @Scotchester My understanding is the pixel values in the visual examples are geared more for visual designers and print but the library will indeed use rems/ems. You'll see currently they show both in the examples, but we'll be building out the one without guides. 

I think it could be cool to toggle to see the guides or just have a separate style guide for print designers. Open to suggestions.
  
![accordions_ui_v1](https://cloud.githubusercontent.com/assets/5249443/8364956/ccf5e2f6-1b3e-11e5-9694-06bdfb4e7108.png)

**Comment by mjovel** [comment]
I would suggest if you are to use pixels that it be kept to the sketch/photoshop prototyping libraries that I believe was being rolled out alongside the library.  I think it would be of greatest utility to non-coding designers who can decipher rems/ems in css/sass. Although, it would likely come with the understanding that there will not be pixel perfection on the interactive versions. Part of the confusion I am feeling is that by currently seeing the guides it makes it a little harder to react to the components themselves. I am feeling torn between the feeling that I am looking at a printed styleguide and an interactive one.

**Comment by carodew** [comment]
@mjovel – good points. I think that's something we'll need to consider moving forward.

**Comment by mollieru** [comment]
This is all really helpful input! @mjovel I think some of the confusion may be derived from that in _this_ iteration, we are displaying the components as flat, non-interactive mock ups. In the next release, the .pngs of the patterns will be replaced by working, interactive coded-out patterns, with code snippets, etc. underneath. 

That said, if I understand your advice, sounds like you're thinking we should maybe save the view of a pattern with guides and padding for the editable art files?

**Comment by mjovel** [comment]
@mollieru - correct. I think those who visit from the web based pattern library would be more likely to use web inspector to gather that information if needed. It would probably be more useful for those using the editable art files so that they could get a sense of measurement as they layout their art file based mock-ups.

In regard to the non-interactive mock-ups I kind of like the single page sticker sheet referenced in #98. It made it a little easier to digest the mock-ups and I felt that the guides kind of got in the way of being able to respond to them. I think that would be a good scenario in which being able to toggle guides on and off would be good.

**Comment by jenniferthibault** [comment]
Would this be a helpful bridge between flat and interactive mockups? Even though many folks would still use the inspector, it could give you a rough idea of both up front. 

(em equivalent measurements not accurate in this quick mockup)

![screen shot 2015-06-26 at 12 59 04 pm](https://cloud.githubusercontent.com/assets/11636908/8384257/d70656a2-1c0d-11e5-948e-a046e9179d94.png)

**Comment by mollieru** [comment]
Cool idea @mjovel ! Could I request you open a new issue w the feature
request to toggle guides on and off?

**Comment by mollieru** [comment]
That seems handy!

I think this gives us some good direction on the need to provide 'ems' to
for interactive elements and 'pixels' for design files.

**Comment by maya** [comment]
@mollieru maybe we can validate this a bit more with user testing before adding it as a feature? @colinpmacarthur @carodew

**Comment by mjovel** [comment]
I agree with @maya that further validation would be a good thing before adding it as a feature. It would likely be a sizeable lift for unknown value return. Actually, what I intended with the toggled functionality guides was on the editable art files and not the online pattern guide itself.

**Comment by mollieru** [comment]
@mjovel sounds good -- thanks for the clarification

**Comment by dannychapman** [comment]
Thanks all! Love the idea of using both pixels and ems. pixems?

**Comment by carodew** [comment]
Based on user research this sprint, there isn't a clear preference for notations being marked in pixels or ems so long as they're ems in the code. Closing the issue. Thanks!
