### ISSUE TITLE
Universal box-sizing rule should be updated

### ISSUE THREAD

**Issue by Scotchester** [18F/govt-wide-patternlibrary#83]
Re: https://github.com/18F/govt-wide-patternlibrary/blob/18f-pages-staging/assets/_scss/core/_base.scss#L1-L3

The most current recommended code can be seen on [Paul Irish's article](http://www.paulirish.com/2012/box-sizing-border-box-ftw/).

**Comment by carodew** [comment]
Whoops – went back to an open browser tab and didn't check to see which one it is. :stuck_out_tongue_winking_eye:

**Comment by maya** [comment]
Thanks @Scotchester. Let me know if https://github.com/18F/govt-wide-patternlibrary/pull/88 looks right to you.
