### ISSUE TITLE
Feedback: Add simple "How to use" a pattern library

### ISSUE THREAD

**Issue by bwillman** [18F/govt-wide-patternlibrary#84]
I'm sure this is already planned, but it might be nice to include a "how to use this if you're a ..." [developer] or [designer], etc. and for those who are using something like this for the first time. 

I suspect those two user types come at it differently - and as a developer, I haven't really used these types of site-wide pattern libraries before.

**Comment by carodew** [comment]
That's a great suggestion! What kinds of content do you think pages like this should contain? What kinds of struggles have you seen designers and developers have with pattern libraries?

**Comment by juliaelman** [comment]
@bwillman great suggestion! #9 is an issue already open for this an appreciate the feedback on how we should frame the docs too. Adding these suggestions to that issue as reference.
