### ISSUE TITLE
Write basic set of docs to explain how to use the pattern library

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#9]
We'll need to write up some documentation that goes over (possibly step by step) how utilize the pattern library on their projects. We won't be able to really start on this until Sprint 3 or so, but want to make sure to get an issue on here.

**Comment by juliaelman** [comment]
Suggestion from @bwillman #84:

I'm sure this is already planned, but it might be nice to include a "how to use this if you're a ..." [developer] or [designer], etc. and for those who are using something like this for the first time.

I suspect those two user types come at it differently - and as a developer, I haven't really used these types of site-wide pattern libraries before.

**Comment by carodew** [comment]
Moving to backlog.
