### ISSUE TITLE
Feature request: Framework Support

### ISSUE THREAD

**Issue by dannychapman** [18F/govt-wide-patternlibrary#96]
Not sure what the appropriate answer is here, but since so many agencies are using Foundation and Bootstrap, any thoughts in terms of integration?

**Comment by juliaelman** [comment]
@dannychapman thanks for putting this out there! First step would be to determine how many government websites currently use or plan on leveraging those frameworks. From there we'd be able to make a more informed decision on whether or not to pursue working on this. Any suggestions on how we can collect that data?

**Comment by carodew** [comment]
We got some inconclusive feedback in interviews so far – as many people did not use these frameworks as did from the people we talked to (although if only half of websites use those frameworks it may be worth supporting). However I don't think we had a good enough sample in the first round to draw strong conclusions from that. It seems a number of agencies are also using Drupal, too, so we should consider that.

**Comment by dannychapman** [comment]
It's really a question of integration or not. I don't think you want to create dependencies on any framework, so perhaps it's just alternate code snippets that leverage / augment existing framework modules. Or, as a baseline, confirming that nothing built conflicts with either framework.

**Comment by maya** [comment]
@dannychapman Yes! I think it's totally correct that our pattern library will not conflict with any framework as we plant to namespace our classes. Framework support sounds out of scope at this phase of the project.

**Comment by dannychapman** [comment]
OK, makes sense. As long as testing is in place to ensure it doesn't conflict with anything, I'm good with that.

**Comment by cew821** [comment]
I suspect there would be a high overlap between the teams likely to adopt a pattern library like this in the near-medium term and teams that are already using a framework like Bourbon/Bootstrap/Foundation etc.

So I am strongly +1 in having an answer for how the eventual end product of this could be integrated with some of the major frameworks out there, because I think that would speed adoption especially among teams that are already comfortable with integrating these types of frameworks.

I also don't think it's necessarily the case that we should be agnostic about which framework(s) we support. It would be OK with me if we __pick__ the framework we think is best, and add this pattern library on top of it.

**Comment by lukefretwell** [comment]
FWIW, we're working on a project related to local government sites where the front-end is built on Bootstrap, and the dev team has discussed integrating the work you're doing here with that. 

cc @jlyon

**Comment by maya** [comment]
@cew821 this library is using Bourbon, bc it's a simple, lightweight library. It also uses Neat, Bourbon's lightweight grid system. Our components will be modular enough that it won't conflict with any of the frameworks you are using.

"Bourbon is a Sass mixin library that simplifies the creation of cross-browser compatible stylesheets. Sass mixins are basically functions and thus only add to a CSS file’s size when they are used by other style rules. As a result, Bourbon is very lightweight by default."

We did not want the library to be tied to a heavy framework, but wanted to build something lean, modular, and reusable. More research will need to be done around frameworks to make a more informed decision on providing support. It may make more sense to allow people who want to use this on different frameworks to fork our library for their use. Or just cherry pick what they need. Stay tuned!

**Comment by carodew** [comment]
So far, user research has indicated that people are using a wide variety of frameworks – Bootstrap is mentioned a lot but just as many people don't want to work on Bootstrap at all, so we definitely don't want to require that framework to use this library. The front end stack (from what we've discovered so far) varies widely across agency websites.

**Comment by dannychapman** [comment]
@carodew Makes sense. As long as there is a good effort made to not conflict, I think we're good!

**Comment by mjovel** [comment]
I think much of the work being done on the framework associated with this pattern library is tackling many of the same problems of a bootstrap or a foundation except with a more accessible and gov focused mentality. I think dependency on bootstrap or foundation would be a bad idea. If however compatibility is what you are looking for. I think there needs to be determined at what level that compatibility begins given the modular nature of the this gov based framework? I kind of agree with @maya that those who are already wed to a framework would be best of cherry picking components they need.

**Comment by carodew** [comment]
Looks like we have consensus that we'll build to not conflict with Bootstrap and Foundation, but not require them as dependencies. Closing the issue! Thanks all!
