### ISSUE TITLE
Feature Request: Complex Tables & Filtering as an element option

### ISSUE THREAD

**Issue by jenniferthibault** [18F/govt-wide-patternlibrary#99]
Really helpful to see basic and complex options for other features, such as navigations. We've been working on basic/advanced filtering layouts for complex tables. Not certain anything is nailed yet, but it's definitely a common feature for platforms dealing with government-scale data:

https://github.com/18F/openFEC-web-app/issues/283#issuecomment-114728448 

(This may be a not-for-alpha thing, but hope it's helpful to know about!)

**Comment by Scotchester** [comment]
Also consider sortable tables.

**Comment by carodew** [comment]
Be sure to check out the wireframe that @KHarshawat submitted in #115 for sortable columns.

**Comment by carodew** [comment]
Moving this feature request into our workflow, thanks for the feedback!
